import React from "react";
import { STRINGS } from "../../constants/string";
import { Column } from "../../components/Column";
import { Row } from "../../components/Row";
import { Text } from "../../components/Text";
import { List } from "../../components/List";
import { Image } from "../../components/Image";
import { Line } from "../../components/Line";
import { Stack } from "../../components/Stack";

const Example5Page = () => {
  return (
    <Column
      className="example5"
      layoutGravity={0}
      gravity={0}
      mainAxisAlignment={"start"}
      crossAxisAlignment={"start"}
      width={1920}
      isExpanded={0}
      left={0}
      right={0}
    >
      <Row
        className="group180"
        layoutGravity={33}
        gravity={0}
        mainAxisAlignment={"start"}
        crossAxisAlignment={"center"}
        width={1920}
        isExpanded={0}
        left={0}
        right={0}
      >
        <Column
          className="copy32"
          layoutGravity={11}
          gravity={0}
          mainAxisAlignment={"center"}
          crossAxisAlignment={"center"}
          width={484}
          isExpanded={0}
          left={0}
          right={0}
        >
          <Text
            className="navigation"
            layoutGravity={12}
            gravity={1}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={340}
            isExpanded={0}
            left={0}
            right={0}
          >
            {STRINGS["lbl_navigation"] || ""}
          </Text>
          <Text
            className="hereisanexam2"
            layoutGravity={12}
            gravity={1}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={340}
            isExpanded={0}
            left={0}
            right={0}
          >
            {STRINGS["msg_here_is_an_exam2"] || ""}
          </Text>
          <Text
            className="thingstotry5"
            layoutGravity={12}
            gravity={1}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={340}
            isExpanded={0}
            left={0}
            right={0}
          >
            {STRINGS["lbl_things_to_try"] || ""}
          </Text>
          <List
            className="group181"
            orientation="vertical"
            layoutGravity={12}
            gravity={0}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={340}
          >
            <Row
              className="step114"
              layoutGravity={1}
              gravity={0}
              mainAxisAlignment={"start"}
              crossAxisAlignment={"start"}
              width={340}
              isExpanded={0}
              left={0}
              right={0}
            >
              <Column
                className="bullet33"
                layoutGravity={11}
                gravity={0}
                mainAxisAlignment={"start"}
                crossAxisAlignment={"start"}
                width={42.67}
                isExpanded={0}
                left={0}
                right={0}
              >
                <Text
                  className="b124"
                  layoutGravity={33}
                  gravity={9}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={42.67}
                  isExpanded={0}
                  left={0}
                  right={0}
                >
                  {STRINGS["lbl_1"] || ""}
                </Text>
              </Column>
              <Text
                className="resizethepare3"
                layoutGravity={11}
                gravity={1}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={276}
                isExpanded={true}
                left={21.330002}
                right={0}
              >
                {STRINGS["msg_resize_the_pare"] || ""}
              </Text>
            </Row>
            <Row
              className="step115"
              layoutGravity={6}
              gravity={0}
              mainAxisAlignment={"start"}
              crossAxisAlignment={"start"}
              width={340}
              isExpanded={0}
              left={0}
              right={0}
            >
              <Column
                className="bullet34"
                layoutGravity={11}
                gravity={0}
                mainAxisAlignment={"start"}
                crossAxisAlignment={"start"}
                width={42.67}
                isExpanded={0}
                left={0}
                right={0}
              >
                <Text
                  className="b213"
                  layoutGravity={33}
                  gravity={9}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={42.67}
                  isExpanded={0}
                  left={0}
                  right={0}
                >
                  {STRINGS["lbl_2"] || ""}
                </Text>
              </Column>
              <Text
                className="inspectthelay"
                layoutGravity={11}
                gravity={1}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={276}
                isExpanded={true}
                left={21.330002}
                right={0}
              >
                {STRINGS["msg_inspect_the_lay"] || ""}
              </Text>
            </Row>
          </List>
        </Column>
        <List
          className="group179"
          orientation="vertical"
          layoutGravity={10}
          gravity={0}
          mainAxisAlignment={""}
          crossAxisAlignment={""}
          width={1334}
        >
          <Row
            className="nav"
            layoutGravity={1}
            gravity={0}
            mainAxisAlignment={"start"}
            crossAxisAlignment={"center"}
            width={1334}
            isExpanded={0}
            left={0}
            right={0}
          >
            <Row
              className="logoframe"
              layoutGravity={10}
              gravity={0}
              mainAxisAlignment={"center"}
              crossAxisAlignment={"center"}
              width={216}
              isExpanded={0}
              left={0}
              right={0}
            >
              <Image
                src="img_logo_3.png"
                alt="Logo"
                className="logo8"
                layoutGravity={11}
                gravity={0}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={60}
                left={0}
                right={0}
              />
              <Text
                className="bolt"
                layoutGravity={10}
                gravity={1}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={53}
                isExpanded={true}
                left={10}
                right={0}
              >
                {STRINGS["lbl_bolt"] || ""}
              </Text>
            </Row>
            <Row
              className="frame1969"
              layoutGravity={10}
              gravity={0}
              mainAxisAlignment={"center"}
              crossAxisAlignment={"start"}
              width={838}
              isExpanded={true}
              left={24}
              right={0}
            >
              <Column
                className="frame1973"
                layoutGravity={11}
                gravity={0}
                mainAxisAlignment={"center"}
                crossAxisAlignment={"start"}
                width={73}
                isExpanded={0}
                left={0}
                right={0}
              >
                <Text
                  className="project"
                  layoutGravity={33}
                  gravity={9}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={73}
                  isExpanded={0}
                  left={0}
                  right={0}
                >
                  {STRINGS["lbl_project"] || ""}
                </Text>
                <Line
                  className="frame1974"
                  layoutGravity={33}
                  gravity={0}
                  isExpanded={0}
                  left={0}
                  right={0}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={73}
                />
              </Column>
              <Text
                className="settings3"
                layoutGravity={11}
                gravity={4}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={86}
                isExpanded={true}
                left={20}
                right={0}
              >
                {STRINGS["lbl_settings"] || ""}
              </Text>
              <Text
                className="help"
                layoutGravity={11}
                gravity={4}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={47}
                isExpanded={0}
                left={20}
                right={0}
              >
                {STRINGS["lbl_help"] || ""}
              </Text>
            </Row>
            <Row
              className="frame1971"
              layoutGravity={10}
              gravity={0}
              mainAxisAlignment={"start"}
              crossAxisAlignment={"center"}
              width={232}
              isExpanded={0}
              left={24}
              right={0}
            >
              <Row
                className="search"
                layoutGravity={11}
                gravity={0}
                mainAxisAlignment={"start"}
                crossAxisAlignment={"center"}
                width={144}
                isExpanded={true}
                left={0}
                right={0}
              >
                <Stack
                  className="group176"
                  layoutGravity={10}
                  gravity={0}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={18}
                  isExpanded={0}
                  left={0}
                  right={0}
                >
                  <div
                    className="ellipse21"
                    layoutGravity={4}
                    gravity={0}
                    width={16}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    isExpanded={0}
                    type="View"
                  ></div>
                  <div
                    className="line22"
                    layoutGravity={7}
                    gravity={0}
                    width={6}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    isExpanded={0}
                    type="View"
                  ></div>
                </Stack>
                <Text
                  className="search2"
                  layoutGravity={10}
                  gravity={1}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={88}
                  isExpanded={true}
                  left={15}
                  right={0}
                >
                  {STRINGS["lbl_search"] || ""}
                </Text>
              </Row>
              <Image
                src="img_frame1970.svg"
                alt="Frame1970"
                className="frame1970"
                layoutGravity={10}
                gravity={0}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={32}
                left={10}
                right={0}
              />
            </Row>
          </Row>
          <Row
            className="nav2"
            layoutGravity={4}
            gravity={0}
            mainAxisAlignment={"start"}
            crossAxisAlignment={"center"}
            width={1334}
            isExpanded={0}
            left={0}
            right={0}
          >
            <Row
              className="logoframe2"
              layoutGravity={10}
              gravity={0}
              mainAxisAlignment={"center"}
              crossAxisAlignment={"center"}
              width={402}
              isExpanded={0}
              left={0}
              right={0}
            >
              <Image
                src="img_logo_3.png"
                alt="Logo"
                className="logo9"
                layoutGravity={11}
                gravity={0}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={60}
                left={0}
                right={0}
              />
              <Text
                className="bolt2"
                layoutGravity={10}
                gravity={1}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={53}
                isExpanded={true}
                left={10}
                right={0}
              >
                {STRINGS["lbl_bolt"] || ""}
              </Text>
            </Row>
            <Row
              className="frame19692"
              layoutGravity={10}
              gravity={0}
              mainAxisAlignment={"center"}
              crossAxisAlignment={"start"}
              width={442}
              isExpanded={true}
              left={24}
              right={0}
            >
              <Column
                className="frame19732"
                layoutGravity={11}
                gravity={0}
                mainAxisAlignment={"center"}
                crossAxisAlignment={"start"}
                width={73}
                isExpanded={0}
                left={0}
                right={0}
              >
                <Text
                  className="project2"
                  layoutGravity={33}
                  gravity={9}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={73}
                  isExpanded={0}
                  left={0}
                  right={0}
                >
                  {STRINGS["lbl_project"] || ""}
                </Text>
                <Line
                  className="frame19742"
                  layoutGravity={33}
                  gravity={0}
                  isExpanded={0}
                  left={0}
                  right={0}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={73}
                />
              </Column>
              <Text
                className="settings4"
                layoutGravity={11}
                gravity={4}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={86}
                isExpanded={true}
                left={20}
                right={0}
              >
                {STRINGS["lbl_settings"] || ""}
              </Text>
              <Text
                className="help2"
                layoutGravity={11}
                gravity={4}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={47}
                isExpanded={0}
                left={20}
                right={0}
              >
                {STRINGS["lbl_help"] || ""}
              </Text>
            </Row>
            <Row
              className="frame19712"
              layoutGravity={10}
              gravity={0}
              mainAxisAlignment={"start"}
              crossAxisAlignment={"center"}
              width={442}
              isExpanded={true}
              left={24}
              right={0}
            >
              <Column
                className="search3"
                layoutGravity={11}
                gravity={0}
                mainAxisAlignment={"start"}
                crossAxisAlignment={"center"}
                width={48}
                isExpanded={true}
                left={0}
                right={0}
              >
                <Stack
                  className="group177"
                  layoutGravity={12}
                  gravity={0}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={18}
                  isExpanded={0}
                  left={0}
                  right={0}
                >
                  <div
                    className="ellipse212"
                    layoutGravity={4}
                    gravity={0}
                    width={16}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    isExpanded={0}
                    type="View"
                  ></div>
                  <div
                    className="line23"
                    layoutGravity={7}
                    gravity={0}
                    width={6}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    isExpanded={0}
                    type="View"
                  ></div>
                </Stack>
              </Column>
              <Image
                src="img_frame1970_1.svg"
                alt="Frame1970"
                className="frame19702"
                layoutGravity={10}
                gravity={0}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={32}
                left={10}
                right={0}
              />
            </Row>
          </Row>
          <Row
            className="nav3"
            layoutGravity={6}
            gravity={0}
            mainAxisAlignment={"start"}
            crossAxisAlignment={"center"}
            width={1334}
            isExpanded={0}
            left={0}
            right={0}
          >
            <Row
              className="logoframe3"
              layoutGravity={10}
              gravity={0}
              mainAxisAlignment={"center"}
              crossAxisAlignment={"center"}
              width={496}
              isExpanded={true}
              left={0}
              right={0}
            >
              <Image
                src="img_logo_3.png"
                alt="Logo"
                className="logo10"
                layoutGravity={11}
                gravity={0}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={60}
                left={0}
                right={0}
              />
              <Text
                className="bolt3"
                layoutGravity={10}
                gravity={1}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={53}
                isExpanded={true}
                left={10}
                right={0}
              >
                {STRINGS["lbl_bolt"] || ""}
              </Text>
            </Row>
            <Row
              className="frame19693"
              layoutGravity={10}
              gravity={0}
              mainAxisAlignment={"start"}
              crossAxisAlignment={"start"}
              width={297}
              isExpanded={0}
              left={10}
              right={0}
            >
              <Column
                className="frame19733"
                layoutGravity={11}
                gravity={0}
                mainAxisAlignment={"center"}
                crossAxisAlignment={"start"}
                width={73}
                isExpanded={0}
                left={0}
                right={0}
              >
                <Text
                  className="project3"
                  layoutGravity={33}
                  gravity={9}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={73}
                  isExpanded={0}
                  left={0}
                  right={0}
                >
                  {STRINGS["lbl_project"] || ""}
                </Text>
                <Line
                  className="frame19743"
                  layoutGravity={33}
                  gravity={0}
                  isExpanded={0}
                  left={0}
                  right={0}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={73}
                />
              </Column>
              <Text
                className="settings5"
                layoutGravity={11}
                gravity={4}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={86}
                isExpanded={true}
                left={20}
                right={0}
              >
                {STRINGS["lbl_settings"] || ""}
              </Text>
            </Row>
            <Row
              className="frame19713"
              layoutGravity={10}
              gravity={0}
              mainAxisAlignment={"start"}
              crossAxisAlignment={"center"}
              width={493}
              isExpanded={0}
              left={24}
              right={0}
            >
              <Column
                className="search4"
                layoutGravity={11}
                gravity={0}
                mainAxisAlignment={"start"}
                crossAxisAlignment={"center"}
                width={48}
                isExpanded={true}
                left={0}
                right={0}
              >
                <Stack
                  className="group178"
                  layoutGravity={12}
                  gravity={0}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={18}
                  isExpanded={0}
                  left={0}
                  right={0}
                >
                  <div
                    className="ellipse213"
                    layoutGravity={4}
                    gravity={0}
                    width={16}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    isExpanded={0}
                    type="View"
                  ></div>
                  <div
                    className="line24"
                    layoutGravity={7}
                    gravity={0}
                    width={6}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    isExpanded={0}
                    type="View"
                  ></div>
                </Stack>
              </Column>
              <Image
                src="img_frame1970_2.svg"
                alt="Frame1970"
                className="frame19703"
                layoutGravity={10}
                gravity={0}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={32}
                left={10}
                right={0}
              />
            </Row>
          </Row>
        </List>
      </Row>
    </Column>
  );
};

export default Example5Page;
