import React from "react";
import { STRINGS } from "../../constants/string";
import { Row } from "../../components/Row";
import { Column } from "../../components/Column";
import { Text } from "../../components/Text";
import { List } from "../../components/List";
import { Image } from "../../components/Image";
import { Stack } from "../../components/Stack";
import { Radio } from "../../components/Radio";

const Example4Page = () => {
  return (
    <Row
      className="example4"
      layoutGravity={0}
      gravity={0}
      mainAxisAlignment={"start"}
      crossAxisAlignment={"center"}
      width={1920}
      isExpanded={0}
      left={0}
      right={0}
    >
      <Column
        className="copy31"
        layoutGravity={11}
        gravity={0}
        mainAxisAlignment={"center"}
        crossAxisAlignment={"center"}
        width={484}
        isExpanded={true}
        left={0}
        right={0}
      >
        <Text
          className="podcastcard"
          layoutGravity={12}
          gravity={1}
          mainAxisAlignment={""}
          crossAxisAlignment={""}
          width={340}
          isExpanded={0}
          left={0}
          right={0}
        >
          {STRINGS["lbl_podcast_card"] || ""}
        </Text>
        <Text
          className="hereisanexam"
          layoutGravity={12}
          gravity={1}
          mainAxisAlignment={""}
          crossAxisAlignment={""}
          width={340}
          isExpanded={0}
          left={0}
          right={0}
        >
          {STRINGS["msg_here_is_an_exam"] || ""}
        </Text>
        <Text
          className="thingstotry4"
          layoutGravity={12}
          gravity={1}
          mainAxisAlignment={""}
          crossAxisAlignment={""}
          width={340}
          isExpanded={0}
          left={0}
          right={0}
        >
          {STRINGS["lbl_things_to_try"] || ""}
        </Text>
        <List
          className="group171"
          orientation="vertical"
          layoutGravity={12}
          gravity={0}
          mainAxisAlignment={""}
          crossAxisAlignment={""}
          width={340}
        >
          <Row
            className="step112"
            layoutGravity={1}
            gravity={0}
            mainAxisAlignment={"start"}
            crossAxisAlignment={"start"}
            width={340}
            isExpanded={0}
            left={0}
            right={0}
          >
            <Column
              className="bullet31"
              layoutGravity={11}
              gravity={0}
              mainAxisAlignment={"start"}
              crossAxisAlignment={"start"}
              width={42.67}
              isExpanded={0}
              left={0}
              right={0}
            >
              <Text
                className="b123"
                layoutGravity={33}
                gravity={9}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={42.67}
                isExpanded={0}
                left={0}
                right={0}
              >
                {STRINGS["lbl_1"] || ""}
              </Text>
            </Column>
            <Text
              className="resizethepare2"
              layoutGravity={11}
              gravity={1}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={276}
              isExpanded={true}
              left={21.330002}
              right={0}
            >
              {STRINGS["msg_resize_the_pare2"] || ""}
            </Text>
          </Row>
          <Row
            className="step113"
            layoutGravity={6}
            gravity={0}
            mainAxisAlignment={"start"}
            crossAxisAlignment={"start"}
            width={340}
            isExpanded={0}
            left={0}
            right={0}
          >
            <Column
              className="bullet32"
              layoutGravity={11}
              gravity={0}
              mainAxisAlignment={"start"}
              crossAxisAlignment={"start"}
              width={42.67}
              isExpanded={0}
              left={0}
              right={0}
            >
              <Text
                className="b212"
                layoutGravity={33}
                gravity={9}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={42.67}
                isExpanded={0}
                left={0}
                right={0}
              >
                {STRINGS["lbl_2"] || ""}
              </Text>
            </Column>
            <Text
              className="addmoretextt2"
              layoutGravity={11}
              gravity={1}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={276}
              isExpanded={true}
              left={21.330002}
              right={0}
            >
              {STRINGS["msg_add_more_text_t3"] || ""}
            </Text>
          </Row>
        </List>
      </Column>
      <Column
        className="cardstack"
        layoutGravity={10}
        gravity={0}
        mainAxisAlignment={"start"}
        crossAxisAlignment={"start"}
        width={375}
        isExpanded={0}
        left={10}
        right={0}
      >
        <List
          className="group172"
          orientation="vertical"
          layoutGravity={33}
          gravity={0}
          mainAxisAlignment={""}
          crossAxisAlignment={""}
          width={375}
        >
          <Column
            className="card3"
            layoutGravity={1}
            gravity={0}
            mainAxisAlignment={"center"}
            crossAxisAlignment={"center"}
            width={375}
            isExpanded={0}
            left={0}
            right={0}
          >
            <Row
              className="header"
              layoutGravity={33}
              gravity={0}
              mainAxisAlignment={"start"}
              crossAxisAlignment={"center"}
              width={375}
              isExpanded={0}
              left={0}
              right={0}
            >
              <Image
                src="img_applocation.svg"
                alt="applocation"
                className="applocation"
                layoutGravity={11}
                gravity={0}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={72}
                left={0}
                right={0}
              />
              <Column
                className="titleinfo"
                layoutGravity={10}
                gravity={0}
                mainAxisAlignment={"start"}
                crossAxisAlignment={"start"}
                width={231}
                isExpanded={true}
                left={24}
                right={0}
              >
                <Text
                  className="title2"
                  layoutGravity={33}
                  gravity={1}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={231}
                  isExpanded={0}
                  left={0}
                  right={0}
                >
                  {STRINGS["msg_8pt_grids_and_b"] || ""}
                </Text>
                <Text
                  className="apr132020"
                  layoutGravity={33}
                  gravity={1}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={231}
                  isExpanded={0}
                  left={0}
                  right={0}
                >
                  {STRINGS["lbl_apr_13_2020"] || ""}
                </Text>
              </Column>
            </Row>
            <Row
              className="frame1953"
              layoutGravity={33}
              gravity={0}
              mainAxisAlignment={"start"}
              crossAxisAlignment={"start"}
              width={375}
              isExpanded={0}
              left={0}
              right={0}
            >
              <Text
                className="f38min"
                layoutGravity={11}
                gravity={1}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={72}
                isExpanded={0}
                left={0}
                right={0}
              >
                {STRINGS["lbl_38_min"] || ""}
              </Text>
              <Text
                className="leveluponeve"
                layoutGravity={11}
                gravity={1}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={231}
                isExpanded={true}
                left={24}
                right={0}
              >
                {STRINGS["msg_level_up_on_eve"] || ""}
              </Text>
            </Row>
            <Text
              className="listennow"
              layoutGravity={12}
              gravity={1}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={327}
              isExpanded={0}
              left={24}
              right={24}
            >
              {STRINGS["lbl_listen_now"] || ""}
            </Text>
          </Column>
          <Column
            className="card4"
            layoutGravity={6}
            gravity={0}
            mainAxisAlignment={"center"}
            crossAxisAlignment={"center"}
            width={375}
            isExpanded={0}
            left={0}
            right={0}
          >
            <Row
              className="header2"
              layoutGravity={33}
              gravity={0}
              mainAxisAlignment={"start"}
              crossAxisAlignment={"center"}
              width={375}
              isExpanded={0}
              left={0}
              right={0}
            >
              <Image
                src="img_applocation_1.svg"
                alt="applocation"
                className="applocation2"
                layoutGravity={11}
                gravity={0}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={72}
                left={0}
                right={0}
              />
              <Column
                className="titleinfo2"
                layoutGravity={10}
                gravity={0}
                mainAxisAlignment={"start"}
                crossAxisAlignment={"start"}
                width={231}
                isExpanded={true}
                left={24}
                right={0}
              >
                <Text
                  className="title3"
                  layoutGravity={33}
                  gravity={1}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={231}
                  isExpanded={0}
                  left={0}
                  right={0}
                >
                  {STRINGS["msg_typography_syst"] || ""}
                </Text>
                <Text
                  className="mar252020"
                  layoutGravity={33}
                  gravity={1}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={231}
                  isExpanded={0}
                  left={0}
                  right={0}
                >
                  {STRINGS["lbl_mar_25_2020"] || ""}
                </Text>
              </Column>
            </Row>
            <Row
              className="frame19532"
              layoutGravity={33}
              gravity={0}
              mainAxisAlignment={"start"}
              crossAxisAlignment={"start"}
              width={375}
              isExpanded={0}
              left={0}
              right={0}
            >
              <Text
                className="f40min"
                layoutGravity={11}
                gravity={1}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={72}
                isExpanded={0}
                left={0}
                right={0}
              >
                {STRINGS["lbl_40_min"] || ""}
              </Text>
              <Text
                className="creatingrespon"
                layoutGravity={11}
                gravity={1}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={231}
                isExpanded={true}
                left={24}
                right={0}
              >
                {STRINGS["msg_creating_respon"] || ""}
              </Text>
            </Row>
            <Text
              className="listennow2"
              layoutGravity={12}
              gravity={1}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={327}
              isExpanded={0}
              left={24}
              right={24}
            >
              {STRINGS["lbl_listen_now"] || ""}
            </Text>
          </Column>
        </List>
        <Column
          className="card5"
          layoutGravity={33}
          gravity={0}
          mainAxisAlignment={"center"}
          crossAxisAlignment={"center"}
          width={375}
          isExpanded={0}
          left={0}
          right={0}
        >
          <Stack
            className="header3"
            layoutGravity={12}
            gravity={0}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={327}
            isExpanded={0}
            left={24}
            right={24}
          >
            <Stack
              className="group170"
              layoutGravity={1}
              gravity={0}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={327}
              isExpanded={0}
              left={0}
              right={0}
            >
              <Image
                src="img_applocation_2.svg"
                alt="applocation"
                className="applocation3"
                layoutGravity={1}
                gravity={0}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={72}
                left={0}
                right={255}
              />
              <Radio
                className="group37"
                label={STRINGS["msg_semantic_color"] || ""}
                name="Group37"
                layoutGravity={5}
                gravity={1}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={287}
              ></Radio>
            </Stack>
            <Radio
              className="group38"
              label={STRINGS["lbl_feb_18_2020"] || ""}
              name="Group38"
              layoutGravity={6}
              gravity={1}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={136}
            ></Radio>
          </Stack>
          <Row
            className="frame19533"
            layoutGravity={33}
            gravity={0}
            mainAxisAlignment={"start"}
            crossAxisAlignment={"start"}
            width={375}
            isExpanded={0}
            left={0}
            right={0}
          >
            <Text
              className="f42min"
              layoutGravity={11}
              gravity={1}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={72}
              isExpanded={0}
              left={0}
              right={0}
            >
              {STRINGS["lbl_42_min"] || ""}
            </Text>
            <Text
              className="movingfromhue"
              layoutGravity={11}
              gravity={1}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={231}
              isExpanded={true}
              left={24}
              right={0}
            >
              {STRINGS["msg_moving_from_hue"] || ""}
            </Text>
          </Row>
          <Text
            className="listennow3"
            layoutGravity={12}
            gravity={1}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={327}
            isExpanded={0}
            left={24}
            right={24}
          >
            {STRINGS["lbl_listen_now"] || ""}
          </Text>
        </Column>
      </Column>
    </Row>
  );
};

export default Example4Page;
