import React from "react";
import { STRINGS } from "../../constants/string";
import { Column } from "../../components/Column";
import { Row } from "../../components/Row";
import { Text } from "../../components/Text";
import { Image } from "../../components/Image";
import { Example1Step3 } from "../../components/Example1Step3";

const AutoLayoutFramesPage = () => {
  return (
    <Column
      className="autolayoutfra"
      layoutGravity={0}
      gravity={0}
      mainAxisAlignment={"start"}
      crossAxisAlignment={"start"}
      width={1920}
      isExpanded={0}
      left={0}
      right={0}
    >
      <Row
        className="group74"
        layoutGravity={33}
        gravity={0}
        mainAxisAlignment={"start"}
        crossAxisAlignment={"center"}
        width={1920}
        isExpanded={0}
        left={0}
        right={0}
      >
        <Column
          className="copy6"
          layoutGravity={11}
          gravity={0}
          mainAxisAlignment={"center"}
          crossAxisAlignment={"center"}
          width={484}
          isExpanded={true}
          left={0}
          right={0}
        >
          <Text
            className="autolayoutfra2"
            layoutGravity={12}
            gravity={1}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={340}
            isExpanded={0}
            left={0}
            right={0}
          >
            {STRINGS["msg_auto_layout_fra"] || ""}
          </Text>
          <Text
            className="youcanaddaut"
            layoutGravity={12}
            gravity={1}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={340}
            isExpanded={0}
            left={0}
            right={0}
          >
            {STRINGS["msg_you_can_add_aut"] || ""}
          </Text>
          <Column
            className="steps"
            layoutGravity={12}
            gravity={0}
            mainAxisAlignment={"start"}
            crossAxisAlignment={"start"}
            width={340}
            isExpanded={0}
            left={0}
            right={0}
          >
            <Row
              className="step1"
              layoutGravity={33}
              gravity={0}
              mainAxisAlignment={"start"}
              crossAxisAlignment={"start"}
              width={340}
              isExpanded={0}
              left={0}
              right={0}
            >
              <Column
                className="bullet4"
                layoutGravity={11}
                gravity={0}
                mainAxisAlignment={"start"}
                crossAxisAlignment={"start"}
                width={42.67}
                isExpanded={0}
                left={0}
                right={0}
              >
                <Text
                  className="b12"
                  layoutGravity={33}
                  gravity={9}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={42.67}
                  isExpanded={0}
                  left={0}
                  right={0}
                >
                  {STRINGS["lbl_1"] || ""}
                </Text>
              </Column>
              <div
                className="group75"
                layoutGravity={11}
                gravity={0}
                width={276}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                isExpanded={true}
                type="HorizontalScroll"
              >
                <Column
                  className="listitem"
                  layoutGravity={1}
                  gravity={0}
                  mainAxisAlignment={"end"}
                  crossAxisAlignment={"start"}
                  width={276}
                  isExpanded={0}
                  left={0}
                  right={0}
                >
                  <Text
                    className="selectthebutt"
                    layoutGravity={12}
                    gravity={1}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={286.67}
                    isExpanded={0}
                    left={0}
                    right={0}
                  >
                    {STRINGS["msg_select_the_butt"] || ""}
                  </Text>
                  <Image
                    src="img_image16_1.png"
                    alt="image16"
                    className="image16"
                    layoutGravity={33}
                    gravity={0}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={240}
                    left={0}
                    right={36}
                  />
                </Column>
              </div>
            </Row>
            <Example1Step3
              children={STRINGS["lbl_2"] || ""}
              children1={STRINGS["msg_you_can_also_ri"] || ""}
            />
          </Column>
        </Column>
        <Column
          className="group73"
          layoutGravity={10}
          gravity={0}
          mainAxisAlignment={"start"}
          crossAxisAlignment={"center"}
          width={265.46997}
          isExpanded={0}
          left={10}
          right={0}
        >
          <div
            className="button3"
            layoutGravity={12}
            gravity={0}
            width={238}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            isExpanded={0}
            type="Card"
          >
            <Text
              className="hiimabutto3"
              layoutGravity={9}
              gravity={1}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={174}
              isExpanded={0}
              left={32}
              right={32}
            >
              {STRINGS["msg_hi_i_m_a_butto"] || ""}
            </Text>
          </div>
          <Column
            className="group72"
            layoutGravity={12}
            gravity={0}
            mainAxisAlignment={"start"}
            crossAxisAlignment={"end"}
            width={265.47}
            isExpanded={0}
            left={0}
            right={0}
          >
            <Image
              src="img_arrow.svg"
              alt="Arrow"
              className="arrow"
              layoutGravity={44}
              gravity={0}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={64.66}
              left={200.81006}
              right={0}
            />
            <Text
              className="selectmeadd"
              layoutGravity={12}
              gravity={3}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={264}
              isExpanded={0}
              left={0}
              right={1.4699707}
            >
              {STRINGS["msg_select_me_add"] || ""}
            </Text>
          </Column>
        </Column>
      </Row>
    </Column>
  );
};

export default AutoLayoutFramesPage;
