import React from "react";
import { STRINGS } from "../../constants/string";
import { Column } from "../../components/Column";
import { Row } from "../../components/Row";
import { Text } from "../../components/Text";
import { Line } from "../../components/Line";
import { Image } from "../../components/Image";
import { List } from "../../components/List";

const ResponsiveContentPage = () => {
  return (
    <Column
      className="responsivecont"
      layoutGravity={0}
      gravity={0}
      mainAxisAlignment={"start"}
      crossAxisAlignment={"start"}
      width={1920}
      isExpanded={0}
      left={0}
      right={0}
    >
      <Row
        className="group104"
        layoutGravity={33}
        gravity={0}
        mainAxisAlignment={"start"}
        crossAxisAlignment={"center"}
        width={1920}
        isExpanded={0}
        left={0}
        right={0}
      >
        <Column
          className="copy14"
          layoutGravity={11}
          gravity={0}
          mainAxisAlignment={"center"}
          crossAxisAlignment={"center"}
          width={484}
          isExpanded={0}
          left={0}
          right={0}
        >
          <Text
            className="responsivecont2"
            layoutGravity={12}
            gravity={1}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={340}
            isExpanded={0}
            left={0}
            right={0}
          >
            {STRINGS["msg_responsive_cont"] || ""}
          </Text>
          <Text
            className="heresacompon"
            layoutGravity={12}
            gravity={1}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={340}
            isExpanded={0}
            left={0}
            right={0}
          >
            {STRINGS["msg_here_s_a_compon"] || ""}
          </Text>
          <Column
            className="tip2"
            layoutGravity={12}
            gravity={0}
            mainAxisAlignment={"start"}
            crossAxisAlignment={"start"}
            width={340}
            isExpanded={0}
            left={0}
            right={0}
          >
            <Line
              className="frame19022"
              layoutGravity={33}
              gravity={0}
              isExpanded={0}
              left={0}
              right={0}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={340}
            />
            <Column
              className="content"
              layoutGravity={33}
              gravity={0}
              mainAxisAlignment={"end"}
              crossAxisAlignment={"center"}
              width={340}
              isExpanded={0}
              left={0}
              right={0}
            >
              <Image
                src="img_image18.png"
                alt="image18"
                className="image18"
                layoutGravity={12}
                gravity={0}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={95}
                left={122.5}
                right={122.5}
              />
              <Text
                className="notetextresi"
                layoutGravity={12}
                gravity={1}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={292}
                isExpanded={0}
                left={24}
                right={24}
              >
                {STRINGS["msg_note_text_resi"] || ""}
              </Text>
              <Line
                className="frame19032"
                layoutGravity={33}
                gravity={0}
                isExpanded={0}
                left={0}
                right={0}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={340}
              />
            </Column>
          </Column>
        </Column>
        <Column
          className="group103"
          layoutGravity={10}
          gravity={0}
          mainAxisAlignment={"start"}
          crossAxisAlignment={"start"}
          width={962}
          isExpanded={true}
          left={237}
          right={0}
        >
          <List
            className="group102"
            orientation="horizontal"
            layoutGravity={33}
            gravity={0}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={962}
          >
            <Column
              className="resizeme"
              layoutGravity={1}
              gravity={0}
              mainAxisAlignment={"start"}
              crossAxisAlignment={"center"}
              width={424}
              isExpanded={0}
              left={0}
              right={538}
            >
              <Column
                className="innercontainer6"
                layoutGravity={12}
                gravity={0}
                mainAxisAlignment={"start"}
                crossAxisAlignment={"start"}
                width={360}
                isExpanded={0}
                left={0}
                right={0}
              >
                <Image
                  src="img_image.png"
                  alt="Image"
                  className="image3"
                  layoutGravity={33}
                  gravity={0}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={360}
                  left={0}
                  right={0}
                />
                <Row
                  className="profile2"
                  layoutGravity={33}
                  gravity={0}
                  mainAxisAlignment={"start"}
                  crossAxisAlignment={"center"}
                  width={360}
                  isExpanded={0}
                  left={0}
                  right={0}
                >
                  <Row
                    className="namehandle2"
                    layoutGravity={11}
                    gravity={0}
                    mainAxisAlignment={"start"}
                    crossAxisAlignment={"center"}
                    width={186}
                    isExpanded={true}
                    left={0}
                    right={0}
                  >
                    <Image
                      src="img_photo_3.svg"
                      alt="Photo"
                      className="photo3"
                      layoutGravity={11}
                      gravity={0}
                      mainAxisAlignment={""}
                      crossAxisAlignment={""}
                      width={56}
                      left={0}
                      right={0}
                    />
                    <Text
                      className="figma2"
                      layoutGravity={10}
                      gravity={1}
                      mainAxisAlignment={""}
                      crossAxisAlignment={""}
                      width={114}
                      isExpanded={true}
                      left={16}
                      right={0}
                    >
                      {STRINGS["lbl_figma"] || ""}
                    </Text>
                  </Row>
                  <Image
                    src="img_iconcomment.svg"
                    alt="IconComment"
                    className="iconcomment7"
                    layoutGravity={10}
                    gravity={0}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={48}
                    left={10}
                    right={0}
                  />
                  <Image
                    src="img_iconlike.svg"
                    alt="IconLike"
                    className="iconlike7"
                    layoutGravity={10}
                    gravity={0}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={48}
                    left={10}
                    right={0}
                  />
                  <Image
                    src="img_iconshare.svg"
                    alt="IconShare"
                    className="iconshare3"
                    layoutGravity={10}
                    gravity={0}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={48}
                    left={10}
                    right={0}
                  />
                </Row>
                <Text
                  className="loremipsumdol"
                  layoutGravity={33}
                  gravity={1}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={360}
                  isExpanded={0}
                  left={0}
                  right={0}
                >
                  {STRINGS["msg_lorem_ipsum_dol"] || ""}
                </Text>
              </Column>
            </Column>
            <Column
              className="resizeme2"
              layoutGravity={2}
              gravity={0}
              mainAxisAlignment={"start"}
              crossAxisAlignment={"center"}
              width={424}
              isExpanded={0}
              left={538}
              right={0}
            >
              <Column
                className="innercontainer7"
                layoutGravity={12}
                gravity={0}
                mainAxisAlignment={"start"}
                crossAxisAlignment={"start"}
                width={360}
                isExpanded={0}
                left={0}
                right={0}
              >
                <Image
                  src="img_image.png"
                  alt="Image"
                  className="image4"
                  layoutGravity={33}
                  gravity={0}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={360}
                  left={0}
                  right={0}
                />
                <Row
                  className="profile3"
                  layoutGravity={33}
                  gravity={0}
                  mainAxisAlignment={"start"}
                  crossAxisAlignment={"center"}
                  width={360}
                  isExpanded={0}
                  left={0}
                  right={0}
                >
                  <Row
                    className="namehandle3"
                    layoutGravity={11}
                    gravity={0}
                    mainAxisAlignment={"start"}
                    crossAxisAlignment={"center"}
                    width={186}
                    isExpanded={true}
                    left={0}
                    right={0}
                  >
                    <Image
                      src="img_photo_3.svg"
                      alt="Photo"
                      className="photo4"
                      layoutGravity={11}
                      gravity={0}
                      mainAxisAlignment={""}
                      crossAxisAlignment={""}
                      width={56}
                      left={0}
                      right={0}
                    />
                    <Text
                      className="figma3"
                      layoutGravity={10}
                      gravity={1}
                      mainAxisAlignment={""}
                      crossAxisAlignment={""}
                      width={114}
                      isExpanded={true}
                      left={16}
                      right={0}
                    >
                      {STRINGS["lbl_figma"] || ""}
                    </Text>
                  </Row>
                  <Image
                    src="img_iconcomment_1.svg"
                    alt="IconComment"
                    className="iconcomment8"
                    layoutGravity={10}
                    gravity={0}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={48}
                    left={10}
                    right={0}
                  />
                  <Image
                    src="img_iconlike_1.svg"
                    alt="IconLike"
                    className="iconlike8"
                    layoutGravity={10}
                    gravity={0}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={48}
                    left={10}
                    right={0}
                  />
                  <Image
                    src="img_iconshare_1.svg"
                    alt="IconShare"
                    className="iconshare4"
                    layoutGravity={10}
                    gravity={0}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={48}
                    left={10}
                    right={0}
                  />
                </Row>
                <Text
                  className="loremipsumdol2"
                  layoutGravity={33}
                  gravity={1}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={360}
                  isExpanded={0}
                  left={0}
                  right={0}
                >
                  {STRINGS["msg_lorem_ipsum_dol"] || ""}
                </Text>
              </Column>
            </Column>
          </List>
          <Row
            className="instructions5"
            layoutGravity={33}
            gravity={0}
            mainAxisAlignment={"end"}
            crossAxisAlignment={"start"}
            width={962}
            isExpanded={0}
            left={0}
            right={0}
          >
            <Text
              className="fixthistobe"
              layoutGravity={11}
              gravity={3}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={327}
              isExpanded={0}
              left={0}
              right={0}
            >
              {STRINGS["msg_fix_this_to_be"] || ""}
            </Text>
            <Row
              className="group1903"
              layoutGravity={11}
              gravity={0}
              mainAxisAlignment={"start"}
              crossAxisAlignment={"center"}
              width={385}
              isExpanded={true}
              left={211}
              right={0}
            >
              <Image
                src="img_arrow_10.svg"
                alt="Arrow"
                className="arrow13"
                layoutGravity={10}
                gravity={0}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={28.5}
                left={0}
                right={0}
              />
              <Text
                className="workingexample"
                layoutGravity={11}
                gravity={3}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={271}
                isExpanded={true}
                left={9.5}
                right={0}
              >
                {STRINGS["msg_working_example"] || ""}
              </Text>
              <Image
                src="img_arrow_11.svg"
                alt="Arrow"
                className="arrow14"
                layoutGravity={10}
                gravity={0}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={28.5}
                left={9}
                right={0}
              />
            </Row>
          </Row>
        </Column>
      </Row>
    </Column>
  );
};

export default ResponsiveContentPage;
