import React from "react";
import { STRINGS } from "../../constants/string";
import { Column } from "../../components/Column";
import { Row } from "../../components/Row";
import { Text } from "../../components/Text";
import { Example1Step2 } from "../../components/Example1Step2";
import { Image } from "../../components/Image";
import { Example1Step3 } from "../../components/Example1Step3";

const Example2Page = () => {
  return (
    <Column
      className="example2"
      layoutGravity={0}
      gravity={0}
      mainAxisAlignment={"start"}
      crossAxisAlignment={"start"}
      width={1920}
      isExpanded={0}
      left={0}
      right={0}
    >
      <Row
        className="group165"
        layoutGravity={33}
        gravity={0}
        mainAxisAlignment={"start"}
        crossAxisAlignment={"center"}
        width={1920}
        isExpanded={0}
        left={0}
        right={0}
      >
        <Column
          className="copy29"
          layoutGravity={11}
          gravity={0}
          mainAxisAlignment={"center"}
          crossAxisAlignment={"center"}
          width={484}
          isExpanded={0}
          left={0}
          right={0}
        >
          <Text
            className="unorderedlist"
            layoutGravity={12}
            gravity={1}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={340}
            isExpanded={0}
            left={0}
            right={0}
          >
            {STRINGS["lbl_unordered_list"] || ""}
          </Text>
          <Text
            className="inthisexample2"
            layoutGravity={12}
            gravity={1}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={340}
            isExpanded={0}
            left={0}
            right={0}
          >
            {STRINGS["msg_in_this_example2"] || ""}
          </Text>
          <Text
            className="thingstotry2"
            layoutGravity={12}
            gravity={1}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={340}
            isExpanded={0}
            left={0}
            right={0}
          >
            {STRINGS["lbl_things_to_try"] || ""}
          </Text>
          <Column
            className="steps8"
            layoutGravity={12}
            gravity={0}
            mainAxisAlignment={"start"}
            crossAxisAlignment={"start"}
            width={340}
            isExpanded={0}
            left={0}
            right={0}
          >
            <Example1Step2
              children={STRINGS["lbl_1"] || ""}
              children1={STRINGS["msg_add_more_text_t"] || ""}
            />
            <Row
              className="step29"
              layoutGravity={33}
              gravity={0}
              mainAxisAlignment={"start"}
              crossAxisAlignment={"start"}
              width={340}
              isExpanded={0}
              left={0}
              right={0}
            >
              <Column
                className="bullet25"
                layoutGravity={11}
                gravity={0}
                mainAxisAlignment={"start"}
                crossAxisAlignment={"start"}
                width={42.67}
                isExpanded={0}
                left={0}
                right={0}
              >
                <Text
                  className="b210"
                  layoutGravity={33}
                  gravity={9}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={42.67}
                  isExpanded={0}
                  left={0}
                  right={0}
                >
                  {STRINGS["lbl_2"] || ""}
                </Text>
              </Column>
              <div
                className="group166"
                layoutGravity={11}
                gravity={0}
                width={276}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                isExpanded={true}
                type="HorizontalScroll"
              >
                <Column
                  className="listitem8"
                  layoutGravity={1}
                  gravity={0}
                  mainAxisAlignment={"end"}
                  crossAxisAlignment={"start"}
                  width={276}
                  isExpanded={0}
                  left={0}
                  right={0}
                >
                  <Text
                    className="editthelisti"
                    layoutGravity={12}
                    gravity={1}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={286.67}
                    isExpanded={0}
                    left={0}
                    right={0}
                  >
                    {STRINGS["msg_edit_the_list_i"] || ""}
                  </Text>
                  <Image
                    src="img_image19.png"
                    alt="image19"
                    className="image19"
                    layoutGravity={33}
                    gravity={0}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={216}
                    left={0}
                    right={60}
                  />
                </Column>
              </div>
            </Row>
            <Example1Step3 children1={STRINGS["msg_adjust_the_spac"] || ""} />
          </Column>
        </Column>
        <Column
          className="group164"
          layoutGravity={10}
          gravity={0}
          mainAxisAlignment={"start"}
          crossAxisAlignment={"start"}
          width={672}
          isExpanded={true}
          left={430}
          right={0}
        >
          <Row
            className="group162"
            layoutGravity={33}
            gravity={0}
            mainAxisAlignment={"end"}
            crossAxisAlignment={"center"}
            width={672}
            isExpanded={0}
            left={0}
            right={0}
          >
            <Image
              src="img_arrow_24.svg"
              alt="Arrow"
              className="arrow30"
              layoutGravity={10}
              gravity={0}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={197.18}
              left={0}
              right={0}
            />
            <Text
              className="tryrestylingt"
              layoutGravity={10}
              gravity={1}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={302}
              isExpanded={true}
              left={33.95996}
              right={0}
            >
              {STRINGS["msg_try_restyling_t"] || ""}
            </Text>
          </Row>
          <Row
            className="listitem9"
            layoutGravity={33}
            gravity={0}
            mainAxisAlignment={"start"}
            crossAxisAlignment={"start"}
            width={672}
            isExpanded={0}
            left={0}
            right={0}
          >
            <Image
              src="img_symbolcontaine.svg"
              alt="symbolcontaine"
              className="symbolcontaine"
              layoutGravity={11}
              gravity={0}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={16}
              left={0}
              right={0}
            />
            <Text
              className="listtext"
              layoutGravity={11}
              gravity={1}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={524}
              isExpanded={true}
              left={16}
              right={0}
            >
              {STRINGS["lbl_hello_there"] || ""}
            </Text>
          </Row>
          <Row
            className="listitem10"
            layoutGravity={33}
            gravity={0}
            mainAxisAlignment={"start"}
            crossAxisAlignment={"start"}
            width={672}
            isExpanded={0}
            left={0}
            right={0}
          >
            <Image
              src="img_symbolcontaine.svg"
              alt="symbolcontaine"
              className="symbolcontaine2"
              layoutGravity={11}
              gravity={0}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={16}
              left={0}
              right={0}
            />
            <Text
              className="listtext2"
              layoutGravity={11}
              gravity={1}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={543}
              isExpanded={true}
              left={16}
              right={0}
            >
              {STRINGS["msg_add_more_text_t2"] || ""}
            </Text>
          </Row>
          <Row
            className="listitem11"
            layoutGravity={33}
            gravity={0}
            mainAxisAlignment={"start"}
            crossAxisAlignment={"start"}
            width={672}
            isExpanded={0}
            left={0}
            right={0}
          >
            <Image
              src="img_symbolcontaine_1.svg"
              alt="symbolcontaine"
              className="symbolcontaine3"
              layoutGravity={11}
              gravity={0}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={16}
              left={0}
              right={0}
            />
            <Text
              className="listtext3"
              layoutGravity={11}
              gravity={1}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={543}
              isExpanded={true}
              left={16}
              right={0}
            >
              {STRINGS["msg_the_text_will_e"] || ""}
            </Text>
          </Row>
          <Row
            className="listitem12"
            layoutGravity={33}
            gravity={0}
            mainAxisAlignment={"start"}
            crossAxisAlignment={"start"}
            width={672}
            isExpanded={0}
            left={0}
            right={0}
          >
            <Image
              src="img_symbolcontaine_1.svg"
              alt="symbolcontaine"
              className="symbolcontaine4"
              layoutGravity={11}
              gravity={0}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={16}
              left={0}
              right={0}
            />
            <Text
              className="listtext4"
              layoutGravity={11}
              gravity={1}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={543}
              isExpanded={true}
              left={16}
              right={0}
            >
              {STRINGS["msg_bonus_try_re_s"] || ""}
            </Text>
          </Row>
        </Column>
      </Row>
    </Column>
  );
};

export default Example2Page;
