import React from "react";
import { STRINGS } from "../../constants/string";
import { Column } from "../../components/Column";
import { Row } from "../../components/Row";
import { Text } from "../../components/Text";
import { Image } from "../../components/Image";
import { Button } from "../../components/Button";

const AutomagicalPage = () => {
  return (
    <Column
      className="automagical4"
      layoutGravity={0}
      gravity={0}
      mainAxisAlignment={"start"}
      crossAxisAlignment={"start"}
      width={1920}
      isExpanded={0}
      left={0}
      right={0}
    >
      <Row
        className="group81"
        layoutGravity={33}
        gravity={0}
        mainAxisAlignment={"start"}
        crossAxisAlignment={"center"}
        width={1920}
        isExpanded={0}
        left={0}
        right={0}
      >
        <Column
          className="copy7"
          layoutGravity={11}
          gravity={0}
          mainAxisAlignment={"center"}
          crossAxisAlignment={"center"}
          width={484}
          isExpanded={0}
          left={0}
          right={0}
        >
          <Text
            className="automagical5"
            layoutGravity={12}
            gravity={1}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={340}
            isExpanded={0}
            left={0}
            right={0}
          >
            {STRINGS["lbl_automagical2"] || ""}
          </Text>
          <Text
            className="whenyouaddau"
            layoutGravity={12}
            gravity={1}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={340}
            isExpanded={0}
            left={0}
            right={0}
          >
            {STRINGS["msg_when_you_add_au"] || ""}
          </Text>
          <Column
            className="steps2"
            layoutGravity={12}
            gravity={0}
            mainAxisAlignment={"start"}
            crossAxisAlignment={"start"}
            width={340}
            isExpanded={0}
            left={0}
            right={0}
          >
            <Row
              className="step12"
              layoutGravity={33}
              gravity={0}
              mainAxisAlignment={"start"}
              crossAxisAlignment={"start"}
              width={340}
              isExpanded={0}
              left={0}
              right={0}
            >
              <Column
                className="bullet6"
                layoutGravity={11}
                gravity={0}
                mainAxisAlignment={"start"}
                crossAxisAlignment={"start"}
                width={42.67}
                isExpanded={0}
                left={0}
                right={0}
              >
                <Text
                  className="b13"
                  layoutGravity={33}
                  gravity={9}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={42.67}
                  isExpanded={0}
                  left={0}
                  right={0}
                >
                  {STRINGS["lbl_1"] || ""}
                </Text>
              </Column>
              <div
                className="group82"
                layoutGravity={11}
                gravity={0}
                width={276}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                isExpanded={true}
                type="HorizontalScroll"
              >
                <Column
                  className="listitem2"
                  layoutGravity={1}
                  gravity={0}
                  mainAxisAlignment={"end"}
                  crossAxisAlignment={"start"}
                  width={276}
                  isExpanded={0}
                  left={0}
                  right={0}
                >
                  <Text
                    className="selectallthre"
                    layoutGravity={12}
                    gravity={1}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={286.67}
                    isExpanded={0}
                    left={0}
                    right={0}
                  >
                    {STRINGS["msg_select_all_thre"] || ""}
                  </Text>
                  <Image
                    src="img_image16_1.png"
                    alt="image16"
                    className="image162"
                    layoutGravity={33}
                    gravity={0}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={240}
                    left={0}
                    right={36}
                  />
                </Column>
              </div>
            </Row>
            <Row
              className="step23"
              layoutGravity={33}
              gravity={0}
              mainAxisAlignment={"start"}
              crossAxisAlignment={"start"}
              width={340}
              isExpanded={0}
              left={0}
              right={0}
            >
              <Column
                className="bullet7"
                layoutGravity={11}
                gravity={0}
                mainAxisAlignment={"start"}
                crossAxisAlignment={"start"}
                width={42.67}
                isExpanded={0}
                left={0}
                right={0}
              >
                <Text
                  className="b23"
                  layoutGravity={33}
                  gravity={9}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={42.67}
                  isExpanded={0}
                  left={0}
                  right={0}
                >
                  {STRINGS["lbl_2"] || ""}
                </Text>
              </Column>
              <Text
                className="selectthetwo"
                layoutGravity={11}
                gravity={1}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={276}
                isExpanded={true}
                left={21.330002}
                right={0}
              >
                {STRINGS["msg_select_the_two"] || ""}
              </Text>
            </Row>
          </Column>
        </Column>
        <Column
          className="group80"
          layoutGravity={10}
          gravity={0}
          mainAxisAlignment={"start"}
          crossAxisAlignment={"center"}
          width={523}
          isExpanded={true}
          left={422}
          right={0}
        >
          <Row
            className="group79"
            layoutGravity={33}
            gravity={0}
            mainAxisAlignment={"start"}
            crossAxisAlignment={"center"}
            width={523}
            isExpanded={0}
            left={0}
            right={0}
          >
            <div
              className="photo2"
              layoutGravity={11}
              gravity={0}
              width={64}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              isExpanded={0}
              type="CircleImage"
            ></div>
            <Text
              className="pedropawson"
              layoutGravity={10}
              gravity={1}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={280}
              isExpanded={true}
              left={26}
              right={0}
            >
              {STRINGS["lbl_pedro_pawson"] || ""}
            </Text>
            <Button
              className="group10"
              layoutGravity={10}
              gravity={9}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={127}
              isExpanded={0}
              left={26}
              right={0}
            >
              {STRINGS["lbl_button"] || ""}
            </Button>
          </Row>
          <Text
            className="adesignplatfo"
            layoutGravity={12}
            gravity={3}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={444}
            isExpanded={0}
            left={39}
            right={40}
          >
            {STRINGS["msg_a_design_platfo"] || ""}
          </Text>
          <Button
            className="group11"
            layoutGravity={12}
            gravity={9}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={127}
            isExpanded={0}
            left={198}
            right={198}
          >
            {STRINGS["lbl_button"] || ""}
          </Button>
        </Column>
        <Column
          className="group78"
          layoutGravity={10}
          gravity={0}
          mainAxisAlignment={"start"}
          crossAxisAlignment={"start"}
          width={415}
          isExpanded={0}
          left={0}
          right={0}
        >
          <Row
            className="group76"
            layoutGravity={33}
            gravity={0}
            mainAxisAlignment={"start"}
            crossAxisAlignment={"center"}
            width={415}
            isExpanded={0}
            left={0}
            right={0}
          >
            <Image
              src="img_arrow_1.svg"
              alt="Arrow"
              className="arrow2"
              layoutGravity={10}
              gravity={0}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={67.9}
              left={0}
              right={0}
            />
            <Text
              className="selectallthre2"
              layoutGravity={22}
              gravity={1}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={319}
              isExpanded={true}
              left={28.099976}
              right={0}
            >
              {STRINGS["msg_select_all_thre2"] || ""}
            </Text>
          </Row>
          <Row
            className="group77"
            layoutGravity={33}
            gravity={0}
            mainAxisAlignment={"start"}
            crossAxisAlignment={"center"}
            width={415}
            isExpanded={0}
            left={0}
            right={0}
          >
            <Image
              src="img_arrow_1.svg"
              alt="Arrow"
              className="arrow3"
              layoutGravity={10}
              gravity={0}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={67.9}
              left={0}
              right={0}
            />
            <Text
              className="selectthesetw"
              layoutGravity={22}
              gravity={1}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={319}
              isExpanded={true}
              left={28.099976}
              right={0}
            >
              {STRINGS["msg_select_these_tw"] || ""}
            </Text>
          </Row>
        </Column>
      </Row>
    </Column>
  );
};

export default AutomagicalPage;
