import React from "react";
import { STRINGS } from "../../constants/string";
import { Column } from "../../components/Column";
import { Row } from "../../components/Row";
import { Text } from "../../components/Text";
import { Button } from "../../components/Button";
import { Image } from "../../components/Image";

const ResizingPage = () => {
  return (
    <Column
      className="resizing4"
      layoutGravity={0}
      gravity={0}
      mainAxisAlignment={"start"}
      crossAxisAlignment={"start"}
      width={1920}
      isExpanded={0}
      left={0}
      right={0}
    >
      <Row
        className="group96"
        layoutGravity={33}
        gravity={0}
        mainAxisAlignment={"start"}
        crossAxisAlignment={"center"}
        width={1920}
        isExpanded={0}
        left={0}
        right={0}
      >
        <Column
          className="copy10"
          layoutGravity={11}
          gravity={0}
          mainAxisAlignment={"center"}
          crossAxisAlignment={"center"}
          width={484}
          isExpanded={0}
          left={0}
          right={0}
        >
          <Text
            className="resizing5"
            layoutGravity={12}
            gravity={1}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={340}
            isExpanded={0}
            left={0}
            right={0}
          >
            {STRINGS["lbl_resizing2"] || ""}
          </Text>
          <Text
            className="resizingoption"
            layoutGravity={12}
            gravity={1}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={340}
            isExpanded={0}
            left={0}
            right={0}
          >
            {STRINGS["msg_resizing_option"] || ""}
          </Text>
        </Column>
        <Column
          className="group95"
          layoutGravity={10}
          gravity={0}
          mainAxisAlignment={"start"}
          crossAxisAlignment={"start"}
          width={1148}
          isExpanded={true}
          left={144}
          right={0}
        >
          <Row
            className="container"
            layoutGravity={33}
            gravity={0}
            mainAxisAlignment={"start"}
            crossAxisAlignment={"center"}
            width={1148}
            isExpanded={0}
            left={0}
            right={0}
          >
            <Button
              className="hug"
              layoutGravity={10}
              gravity={9}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={187}
              isExpanded={0}
              left={0}
              right={0}
            >
              {STRINGS["lbl_hug_contents"] || ""}
            </Button>
            <Column
              className="fillvertically"
              layoutGravity={10}
              gravity={0}
              mainAxisAlignment={"start"}
              crossAxisAlignment={"center"}
              width={166}
              isExpanded={0}
              left={32}
              right={0}
            >
              <Text
                className="fixedwidthfi"
                layoutGravity={12}
                gravity={3}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={146}
                isExpanded={0}
                left={0}
                right={0}
              >
                {STRINGS["msg_fixed_width_f"] || ""}
              </Text>
            </Column>
            <Column
              className="fillhorizontal"
              layoutGravity={10}
              gravity={0}
              mainAxisAlignment={"start"}
              crossAxisAlignment={"center"}
              width={317.5}
              isExpanded={true}
              left={32}
              right={0}
            >
              <Text
                className="fixedheightf"
                layoutGravity={12}
                gravity={3}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={168}
                isExpanded={0}
                left={0}
                right={0}
              >
                {STRINGS["msg_fixed_height"] || ""}
              </Text>
            </Column>
            <Column
              className="fillvertical"
              layoutGravity={10}
              gravity={0}
              mainAxisAlignment={"start"}
              crossAxisAlignment={"center"}
              width={317.5}
              isExpanded={true}
              left={32}
              right={0}
            >
              <Text
                className="fillvertical2"
                layoutGravity={12}
                gravity={3}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={137}
                isExpanded={0}
                left={0}
                right={0}
              >
                {STRINGS["msg_fill_vertical"] || ""}
              </Text>
            </Column>
          </Row>
          <Row
            className="group94"
            layoutGravity={33}
            gravity={0}
            mainAxisAlignment={"center"}
            crossAxisAlignment={"center"}
            width={1148}
            isExpanded={0}
            left={0}
            right={0}
          >
            <Image
              src="img_arrow_5.svg"
              alt="Arrow"
              className="arrow7"
              layoutGravity={11}
              gravity={0}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={38.11}
              left={0}
              right={0}
            />
            <Text
              className="trystretching"
              layoutGravity={22}
              gravity={3}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={442}
              isExpanded={true}
              left={13.130005}
              right={0}
            >
              {STRINGS["msg_try_stretching"] || ""}
            </Text>
          </Row>
        </Column>
      </Row>
    </Column>
  );
};

export default ResizingPage;
