import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/welcome">Welcome</Link>
        </li>
        <li>
          <Link to="/howtouseautolayout">HowtouseAutoLayout</Link>
        </li>
        <li>
          <Link to="/whatisautolayout">WhatisAutoLayout</Link>
        </li>
        <li>
          <Link to="/autolayoutframes">AutoLayoutFrames</Link>
        </li>
        <li>
          <Link to="/automagical">Automagical</Link>
        </li>
        <li>
          <Link to="/adjustingpadding">AdjustingPadding</Link>
        </li>
        <li>
          <Link to="/individualpadding">Individualpadding</Link>
        </li>
        <li>
          <Link to="/resizing">Resizing</Link>
        </li>
        <li>
          <Link to="/resizing1">Resizing1</Link>
        </li>
        <li>
          <Link to="/resizing2">Resizing2</Link>
        </li>
        <li>
          <Link to="/nestedautolayout">NestedAutoLayout</Link>
        </li>
        <li>
          <Link to="/responsivecontent">ResponsiveContent</Link>
        </li>
        <li>
          <Link to="/tables">Tables</Link>
        </li>
        <li>
          <Link to="/distribution">Distribution</Link>
        </li>
        <li>
          <Link to="/alignment">Alignment</Link>
        </li>
        <li>
          <Link to="/inspect">Inspect</Link>
        </li>
        <li>
          <Link to="/puttingitalltogether">Puttingitalltogether</Link>
        </li>
        <li>
          <Link to="/whatsnew">WhatsNew</Link>
        </li>
        <li>
          <Link to="/morelayoutoptions">MoreLayoutOptions</Link>
        </li>
        <li>
          <Link to="/individualpadding">IndividualPadding</Link>
        </li>
        <li>
          <Link to="/alignmentcontrols">AlignmentControls</Link>
        </li>
        <li>
          <Link to="/examples">Examples</Link>
        </li>
        <li>
          <Link to="/example1">Example1</Link>
        </li>
        <li>
          <Link to="/example2">Example2</Link>
        </li>
        <li>
          <Link to="/example3">Example3</Link>
        </li>
        <li>
          <Link to="/example4">Example4</Link>
        </li>
        <li>
          <Link to="/example5">Example5</Link>
        </li>
        <li>
          <Link to="/resources">Resources</Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;
