import React from "react";
import { STRINGS } from "../../constants/string";
import { Column } from "../../components/Column";
import { Text } from "../../components/Text";
import { Row } from "../../components/Row";
import { Button } from "../../components/Button";
import { Image } from "../../components/Image";
import { Stack } from "../../components/Stack";
import { Line } from "../../components/Line";

const ResourcesPage = () => {
  return (
    <Column
      className="resources"
      layoutGravity={0}
      gravity={0}
      mainAxisAlignment={"start"}
      crossAxisAlignment={"start"}
      width={2712}
      isExpanded={0}
      left={0}
      right={0}
    >
      <Column
        className="copy33"
        layoutGravity={33}
        gravity={0}
        mainAxisAlignment={"center"}
        crossAxisAlignment={"center"}
        width={2712}
        isExpanded={0}
        left={0}
        right={0}
      >
        <Text
          className="resources2"
          layoutGravity={33}
          gravity={4}
          mainAxisAlignment={""}
          crossAxisAlignment={""}
          width={672}
          isExpanded={0}
          left={200}
          right={1840}
        >
          {STRINGS["lbl_resources"] || ""}
        </Text>
        <Text
          className="moreresources"
          layoutGravity={33}
          gravity={1}
          mainAxisAlignment={""}
          crossAxisAlignment={""}
          width={820.88}
          isExpanded={0}
          left={200}
          right={1691.12}
        >
          {STRINGS["msg_more_resources"] || ""}
        </Text>
        <Row
          className="callout"
          layoutGravity={33}
          gravity={0}
          mainAxisAlignment={"end"}
          crossAxisAlignment={"center"}
          width={2712}
          isExpanded={0}
          left={0}
          right={0}
        >
          <Column
            className="frame1951"
            layoutGravity={10}
            gravity={0}
            mainAxisAlignment={"start"}
            crossAxisAlignment={"start"}
            width={291}
            isExpanded={0}
            left={0}
            right={0}
          >
            <Column
              className="frame1949"
              layoutGravity={12}
              gravity={0}
              mainAxisAlignment={"start"}
              crossAxisAlignment={"start"}
              width={285}
              isExpanded={0}
              left={0}
              right={6}
            >
              <Text
                className="officehours"
                layoutGravity={33}
                gravity={1}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={188}
                isExpanded={0}
                left={0}
                right={97}
              >
                {STRINGS["lbl_office_hours"] || ""}
              </Text>
              <Text
                className="diveintoauto"
                layoutGravity={33}
                gravity={1}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={285}
                isExpanded={0}
                left={0}
                right={0}
              >
                {STRINGS["msg_dive_into_auto"] || ""}
              </Text>
            </Column>
            <Button
              className="group47"
              layoutGravity={33}
              gravity={9}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={291}
              isExpanded={0}
              left={0}
              right={0}
            >
              {STRINGS["msg_register_for_th"] || ""}
            </Button>
          </Column>
          <Image
            src="img_image20.png"
            alt="image20"
            className="image20"
            layoutGravity={10}
            gravity={0}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={303}
            left={87}
            right={0}
          />
          <Column
            className="callout2"
            layoutGravity={11}
            gravity={0}
            mainAxisAlignment={"center"}
            crossAxisAlignment={"start"}
            width={728}
            isExpanded={true}
            left={79}
            right={0}
          >
            <Row
              className="group188"
              layoutGravity={33}
              gravity={0}
              mainAxisAlignment={"end"}
              crossAxisAlignment={"center"}
              width={728}
              isExpanded={0}
              left={0}
              right={0}
            >
              <Column
                className="frame19512"
                layoutGravity={10}
                gravity={0}
                mainAxisAlignment={"start"}
                crossAxisAlignment={"start"}
                width={406}
                isExpanded={true}
                left={0}
                right={0}
              >
                <Column
                  className="frame19492"
                  layoutGravity={33}
                  gravity={0}
                  mainAxisAlignment={"start"}
                  crossAxisAlignment={"start"}
                  width={406}
                  isExpanded={0}
                  left={0}
                  right={0}
                >
                  <Text
                    className="helpcenter"
                    layoutGravity={33}
                    gravity={1}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={179}
                    isExpanded={0}
                    left={0}
                    right={227}
                  >
                    {STRINGS["lbl_help_center"] || ""}
                  </Text>
                  <Text
                    className="dynamicdesigns"
                    layoutGravity={33}
                    gravity={1}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={406}
                    isExpanded={0}
                    left={0}
                    right={0}
                  >
                    {STRINGS["msg_dynamic_designs"] || ""}
                  </Text>
                </Column>
                <Button
                  className="group48"
                  layoutGravity={33}
                  gravity={9}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={186}
                  isExpanded={0}
                  left={0}
                  right={220}
                >
                  {STRINGS["msg_read_the_articl"] || ""}
                </Button>
              </Column>
              <Column
                className="group187"
                layoutGravity={10}
                gravity={0}
                mainAxisAlignment={"start"}
                crossAxisAlignment={"start"}
                width={236}
                isExpanded={0}
                left={32}
                right={0}
              >
                <Column
                  className="group18382"
                  layoutGravity={33}
                  gravity={0}
                  mainAxisAlignment={"start"}
                  crossAxisAlignment={"center"}
                  width={134.15}
                  isExpanded={0}
                  left={0}
                  right={101.849976}
                >
                  <Column
                    className="rectangle4726"
                    layoutGravity={33}
                    gravity={0}
                    mainAxisAlignment={"start"}
                    crossAxisAlignment={"start"}
                    width={102.33008}
                    isExpanded={0}
                    left={0}
                    right={31.820068}
                  >
                    <Row
                      className="group185"
                      layoutGravity={12}
                      gravity={0}
                      mainAxisAlignment={"start"}
                      crossAxisAlignment={"start"}
                      width={102.33}
                      isExpanded={0}
                      left={0}
                      right={0}
                    >
                      <Row
                        className="ellipse1312"
                        layoutGravity={11}
                        gravity={0}
                        mainAxisAlignment={"start"}
                        crossAxisAlignment={"center"}
                        width={73.52}
                        isExpanded={true}
                        left={0}
                        right={0}
                      >
                        <Image
                          src="img_group1833_5.svg"
                          alt="Group1833"
                          className="group18336"
                          layoutGravity={10}
                          gravity={0}
                          mainAxisAlignment={""}
                          crossAxisAlignment={""}
                          width={10.93}
                          left={0}
                          right={0}
                        />
                        <Text
                          className="go4"
                          layoutGravity={10}
                          gravity={3}
                          mainAxisAlignment={""}
                          crossAxisAlignment={""}
                          width={42.72}
                          isExpanded={true}
                          left={19.869995}
                          right={0}
                        >
                          {STRINGS["lbl_go"] || ""}
                        </Text>
                      </Row>
                      <Image
                        src="img_group1833_5.svg"
                        alt="Group1834"
                        className="group18346"
                        layoutGravity={10}
                        gravity={0}
                        mainAxisAlignment={""}
                        crossAxisAlignment={""}
                        width={10.93}
                        left={10}
                        right={0}
                      />
                    </Row>
                  </Column>
                  <Image
                    src="img_vector80_1.svg"
                    alt="Vector80"
                    className="vector806"
                    layoutGravity={44}
                    gravity={0}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={29.5}
                    left={104.650024}
                    right={0}
                  />
                </Column>
                <div
                  className="group196"
                  layoutGravity={33}
                  gravity={0}
                  width={236}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  isExpanded={0}
                  type="HorizontalScroll"
                >
                  <Stack
                    className="group18392"
                    layoutGravity={4}
                    gravity={0}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={236}
                    isExpanded={0}
                    left={0}
                    right={0}
                  >
                    <Image
                      src="img_rectangle471_2.svg"
                      alt="Rectangle471"
                      className="rectangle4715"
                      layoutGravity={5}
                      gravity={0}
                      mainAxisAlignment={""}
                      crossAxisAlignment={""}
                      width={238.58}
                      left={44.31006}
                      right={0}
                    />
                    <Stack
                      className="group44"
                      layoutGravity={5}
                      gravity={0}
                      mainAxisAlignment={""}
                      crossAxisAlignment={""}
                      width={288.8501}
                      isExpanded={0}
                      left={0}
                      right={0}
                    >
                      <Stack
                        className="group186"
                        layoutGravity={1}
                        gravity={0}
                        mainAxisAlignment={""}
                        crossAxisAlignment={""}
                        width={288.8501}
                        isExpanded={0}
                        left={0}
                        right={0}
                      >
                        <Image
                          src="img_rectangle472_1.svg"
                          alt="Rectangle472"
                          className="rectangle4727"
                          layoutGravity={5}
                          gravity={0}
                          mainAxisAlignment={""}
                          crossAxisAlignment={""}
                          width={243.55}
                          left={41.329956}
                          right={3.9699707}
                        />
                        <Image
                          src="img_group1833_6.svg"
                          alt="Group1833"
                          className="group18337"
                          layoutGravity={5}
                          gravity={0}
                          mainAxisAlignment={""}
                          crossAxisAlignment={""}
                          width={10.93}
                          left={277.92004}
                          right={0}
                        />
                        <Image
                          src="img_group1834_3.svg"
                          alt="Group1834"
                          className="group18347"
                          layoutGravity={4}
                          gravity={0}
                          mainAxisAlignment={""}
                          crossAxisAlignment={""}
                          width={10.93}
                          left={36.410034}
                          right={241.50989}
                        />
                        <Line
                          className="vector807"
                          layoutGravity={4}
                          gravity={0}
                          isExpanded={0}
                          left={0}
                          right={247.13}
                          mainAxisAlignment={""}
                          crossAxisAlignment={""}
                          width={41.72}
                        />
                      </Stack>
                      <Text
                        className="go5"
                        layoutGravity={5}
                        gravity={3}
                        mainAxisAlignment={""}
                        crossAxisAlignment={""}
                        width={42.72}
                        isExpanded={0}
                        left={141.67004}
                        right={104.45996}
                      >
                        {STRINGS["lbl_go"] || ""}
                      </Text>
                    </Stack>
                  </Stack>
                </div>
              </Column>
            </Row>
          </Column>
          <Column
            className="callout3"
            layoutGravity={11}
            gravity={0}
            mainAxisAlignment={"start"}
            crossAxisAlignment={"center"}
            width={728}
            isExpanded={true}
            left={64}
            right={0}
          >
            <div
              className="group197"
              layoutGravity={44}
              gravity={0}
              width={696}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              isExpanded={0}
              type="HorizontalScroll"
            >
              <Stack
                className="group193"
                layoutGravity={4}
                gravity={0}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={696}
                isExpanded={0}
                left={0}
                right={0}
              >
                <Stack
                  className="group18393"
                  layoutGravity={4}
                  gravity={0}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={658.6399}
                  isExpanded={0}
                  left={0}
                  right={37.359863}
                >
                  <Stack
                    className="group183"
                    layoutGravity={1}
                    gravity={0}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={658.6399}
                    isExpanded={0}
                    left={0}
                    right={0}
                  >
                    <Column
                      className="frame19513"
                      layoutGravity={4}
                      gravity={0}
                      mainAxisAlignment={"start"}
                      crossAxisAlignment={"start"}
                      width={451}
                      isExpanded={0}
                      left={0}
                      right={207.64014}
                    >
                      <Column
                        className="frame19493"
                        layoutGravity={33}
                        gravity={0}
                        mainAxisAlignment={"start"}
                        crossAxisAlignment={"start"}
                        width={451}
                        isExpanded={0}
                        left={0}
                        right={0}
                      >
                        <Text
                          className="blog"
                          layoutGravity={33}
                          gravity={1}
                          mainAxisAlignment={""}
                          crossAxisAlignment={""}
                          width={68}
                          isExpanded={0}
                          left={0}
                          right={383}
                        >
                          {STRINGS["lbl_blog"] || ""}
                        </Text>
                        <Text
                          className="themakingoft"
                          layoutGravity={33}
                          gravity={1}
                          mainAxisAlignment={""}
                          crossAxisAlignment={""}
                          width={451}
                          isExpanded={0}
                          left={0}
                          right={0}
                        >
                          {STRINGS["msg_the_making_of_t"] || ""}
                        </Text>
                      </Column>
                      <Button
                        className="group49"
                        layoutGravity={33}
                        gravity={9}
                        mainAxisAlignment={""}
                        crossAxisAlignment={""}
                        width={186}
                        isExpanded={0}
                        left={0}
                        right={265}
                      >
                        {STRINGS["msg_read_the_articl"] || ""}
                      </Button>
                    </Column>
                    <Stack
                      className="group192"
                      layoutGravity={7}
                      gravity={0}
                      mainAxisAlignment={""}
                      crossAxisAlignment={""}
                      width={236.64014}
                      isExpanded={0}
                      left={422}
                      right={0.00024414062}
                    >
                      <Stack
                        className="group46"
                        layoutGravity={1}
                        gravity={0}
                        mainAxisAlignment={""}
                        crossAxisAlignment={""}
                        width={202.79004}
                        isExpanded={0}
                        left={0}
                        right={33.849854}
                      >
                        <Stack
                          className="group190"
                          layoutGravity={1}
                          gravity={0}
                          mainAxisAlignment={""}
                          crossAxisAlignment={""}
                          width={202.79004}
                          isExpanded={0}
                          left={0}
                          right={0}
                        >
                          <Image
                            src="img_rectangle472_2.svg"
                            alt="Rectangle472"
                            className="rectangle4728"
                            layoutGravity={9}
                            gravity={0}
                            mainAxisAlignment={""}
                            crossAxisAlignment={""}
                            width={199.53}
                            left={3.2600098}
                            right={0}
                          />
                          <Image
                            src="img_group1833_7.svg"
                            alt="Group1833"
                            className="group18338"
                            layoutGravity={4}
                            gravity={0}
                            mainAxisAlignment={""}
                            crossAxisAlignment={""}
                            width={8.95}
                            left={0}
                            right={193.84009}
                          />
                        </Stack>
                        <Text
                          className="go6"
                          layoutGravity={9}
                          gravity={3}
                          mainAxisAlignment={""}
                          crossAxisAlignment={""}
                          width={35}
                          isExpanded={0}
                          left={85.59009}
                          right={82.19995}
                        >
                          {STRINGS["lbl_go"] || ""}
                        </Text>
                      </Stack>
                      <Stack
                        className="group191"
                        layoutGravity={5}
                        gravity={0}
                        mainAxisAlignment={""}
                        crossAxisAlignment={""}
                        width={38.78}
                        isExpanded={0}
                        left={197.8601}
                        right={0}
                      >
                        <Image
                          src="img_group1833_7.svg"
                          alt="Group1834"
                          className="group18348"
                          layoutGravity={1}
                          gravity={0}
                          mainAxisAlignment={""}
                          crossAxisAlignment={""}
                          width={8.95}
                          left={0}
                          right={29.830078}
                        />
                        <Line
                          className="vector808"
                          layoutGravity={5}
                          gravity={0}
                          isExpanded={0}
                          left={4.5998535}
                          right={0.00024414062}
                          mainAxisAlignment={""}
                          crossAxisAlignment={""}
                          width={34.18}
                        />
                      </Stack>
                    </Stack>
                  </Stack>
                  <Image
                    src="img_rectangle471_3.svg"
                    alt="Rectangle471"
                    className="rectangle4716"
                    layoutGravity={7}
                    gravity={0}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={195.46}
                    left={426.87988}
                    right={36.300293}
                  />
                </Stack>
                <Stack
                  className="rectangle4729"
                  layoutGravity={5}
                  gravity={0}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={261.25977}
                  isExpanded={0}
                  left={511.3601}
                  right={0}
                >
                  <Stack
                    className="group189"
                    layoutGravity={1}
                    gravity={0}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={261.25977}
                    isExpanded={0}
                    left={0}
                    right={0}
                  >
                    <Stack
                      className="group194"
                      layoutGravity={9}
                      gravity={0}
                      mainAxisAlignment={""}
                      crossAxisAlignment={""}
                      width={255.55981}
                      isExpanded={0}
                      left={0}
                      right={5.699951}
                    >
                      <div
                        className="rectangle4717"
                        layoutGravity={9}
                        gravity={0}
                        width={250.68}
                        mainAxisAlignment={""}
                        crossAxisAlignment={""}
                        isExpanded={0}
                        type="View"
                      ></div>
                      <Image
                        src="img_group1833_8.svg"
                        alt="Group1833"
                        className="group18339"
                        layoutGravity={4}
                        gravity={0}
                        mainAxisAlignment={""}
                        crossAxisAlignment={""}
                        width={8.96}
                        left={0}
                        right={246.6001}
                      />
                    </Stack>
                    <Image
                      src="img_group1834_4.svg"
                      alt="Group1834"
                      className="group18349"
                      layoutGravity={5}
                      gravity={0}
                      mainAxisAlignment={""}
                      crossAxisAlignment={""}
                      width={8.95}
                      left={252.30981}
                      right={0.00024414062}
                    />
                    <Line
                      className="vector809"
                      layoutGravity={8}
                      gravity={0}
                      isExpanded={0}
                      left={131.02979}
                      right={127.79028}
                      mainAxisAlignment={""}
                      crossAxisAlignment={""}
                      width={2.44}
                    />
                  </Stack>
                  <Text
                    className="gogogo2"
                    layoutGravity={9}
                    gravity={3}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={35}
                    isExpanded={0}
                    left={113.12988}
                    right={113.13013}
                  >
                    {STRINGS["lbl_go_go_go"] || ""}
                  </Text>
                </Stack>
              </Stack>
            </div>
          </Column>
        </Row>
      </Column>
    </Column>
  );
};

export default ResourcesPage;
