import React from "react";
import { STRINGS } from "../../constants/string";
import { Column } from "../../components/Column";
import { Row } from "../../components/Row";
import { Text } from "../../components/Text";
import { Image } from "../../components/Image";

const WhatisAutoLayoutPage = () => {
  return (
    <Column
      className="whatisautola"
      layoutGravity={0}
      gravity={0}
      mainAxisAlignment={"start"}
      crossAxisAlignment={"start"}
      width={1920}
      isExpanded={0}
      left={0}
      right={0}
    >
      <Row
        className="group71"
        layoutGravity={33}
        gravity={0}
        mainAxisAlignment={"start"}
        crossAxisAlignment={"center"}
        width={1920}
        isExpanded={0}
        left={0}
        right={0}
      >
        <Column
          className="instructions"
          layoutGravity={11}
          gravity={0}
          mainAxisAlignment={"start"}
          crossAxisAlignment={"center"}
          width={960}
          isExpanded={true}
          left={0}
          right={0}
        >
          <Column
            className="copy5"
            layoutGravity={12}
            gravity={0}
            mainAxisAlignment={"start"}
            crossAxisAlignment={"start"}
            width={816}
            isExpanded={0}
            left={0}
            right={0}
          >
            <Text
              className="whatisautola2"
              layoutGravity={33}
              gravity={1}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={816}
              isExpanded={0}
              left={0}
              right={0}
            >
              {STRINGS["msg_what_is_auto_la"] || ""}
            </Text>
            <Text
              className="autolayoutlet"
              layoutGravity={33}
              gravity={1}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={816}
              isExpanded={0}
              left={0}
              right={0}
            >
              {STRINGS["msg_auto_layout_let"] || ""}
            </Text>
          </Column>
        </Column>
        <Column
          className="group70"
          layoutGravity={10}
          gravity={0}
          mainAxisAlignment={"start"}
          crossAxisAlignment={"start"}
          width={424}
          isExpanded={0}
          left={10}
          right={0}
        >
          <div
            className="button"
            layoutGravity={33}
            gravity={0}
            width={238}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            isExpanded={0}
            type="Card"
          >
            <Text
              className="hiimabutto"
              layoutGravity={9}
              gravity={1}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={174}
              isExpanded={0}
              left={32}
              right={32}
            >
              {STRINGS["msg_hi_i_m_a_butto"] || ""}
            </Text>
          </div>
          <div
            className="button2"
            layoutGravity={12}
            gravity={0}
            width={413}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            isExpanded={0}
            type="Card"
          >
            <Text
              className="hiimabutto2"
              layoutGravity={9}
              gravity={1}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={349}
              isExpanded={0}
              left={32}
              right={32}
            >
              {STRINGS["msg_hi_i_m_a_butto2"] || ""}
            </Text>
          </div>
          <Column
            className="card"
            layoutGravity={33}
            gravity={0}
            mainAxisAlignment={"start"}
            crossAxisAlignment={"center"}
            width={424}
            isExpanded={0}
            left={0}
            right={0}
          >
            <Column
              className="innercontainer"
              layoutGravity={12}
              gravity={0}
              mainAxisAlignment={"start"}
              crossAxisAlignment={"start"}
              width={360}
              isExpanded={0}
              left={0}
              right={0}
            >
              <Image
                src="img_image.png"
                alt="Image"
                className="image2"
                layoutGravity={33}
                gravity={0}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={360}
                left={0}
                right={0}
              />
              <Row
                className="profile"
                layoutGravity={33}
                gravity={0}
                mainAxisAlignment={"start"}
                crossAxisAlignment={"center"}
                width={360}
                isExpanded={0}
                left={0}
                right={0}
              >
                <Row
                  className="namehandle"
                  layoutGravity={11}
                  gravity={0}
                  mainAxisAlignment={"start"}
                  crossAxisAlignment={"center"}
                  width={186}
                  isExpanded={true}
                  left={0}
                  right={0}
                >
                  <Image
                    src="img_photo_2.svg"
                    alt="Photo"
                    className="photo"
                    layoutGravity={11}
                    gravity={0}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={56}
                    left={0}
                    right={0}
                  />
                  <Text
                    className="figma"
                    layoutGravity={10}
                    gravity={1}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={114}
                    isExpanded={true}
                    left={16}
                    right={0}
                  >
                    {STRINGS["lbl_figma"] || ""}
                  </Text>
                </Row>
                <Image
                  src="img_iconcomment.svg"
                  alt="IconComment"
                  className="iconcomment2"
                  layoutGravity={10}
                  gravity={0}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={48}
                  left={10}
                  right={0}
                />
                <Image
                  src="img_iconlike.svg"
                  alt="IconLike"
                  className="iconlike2"
                  layoutGravity={10}
                  gravity={0}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={48}
                  left={10}
                  right={0}
                />
                <Image
                  src="img_iconshare.svg"
                  alt="IconShare"
                  className="iconshare2"
                  layoutGravity={10}
                  gravity={0}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={48}
                  left={10}
                  right={0}
                />
              </Row>
              <Text
                className="hiimacard"
                layoutGravity={33}
                gravity={1}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={360}
                isExpanded={0}
                left={0}
                right={0}
              >
                {STRINGS["msg_hi_i_m_a_card"] || ""}
              </Text>
            </Column>
          </Column>
        </Column>
      </Row>
    </Column>
  );
};

export default WhatisAutoLayoutPage;
