import React from "react";
import { STRINGS } from "../../constants/string";
import { Column } from "../../components/Column";
import { Row } from "../../components/Row";
import { Alignmentcopy } from "../../components/Alignmentcopy";
import { Stack } from "../../components/Stack";
import { Image } from "../../components/Image";
import { Text } from "../../components/Text";

const DistributionPage = () => {
  return (
    <Column
      className="distribution4"
      layoutGravity={0}
      gravity={0}
      mainAxisAlignment={"start"}
      crossAxisAlignment={"start"}
      width={1920}
      isExpanded={0}
      left={0}
      right={0}
    >
      <Row
        className="group114"
        layoutGravity={33}
        gravity={0}
        mainAxisAlignment={"start"}
        crossAxisAlignment={"center"}
        width={1920}
        isExpanded={0}
        left={0}
        right={0}
      >
        <Column
          className="group111"
          layoutGravity={11}
          gravity={0}
          mainAxisAlignment={"start"}
          crossAxisAlignment={"center"}
          width={484}
          isExpanded={0}
          left={0}
          right={0}
        >
          <Stack
            className="group115"
            layoutGravity={12}
            gravity={0}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={340}
            isExpanded={0}
            left={0}
            right={0}
          >
            <Alignmentcopy
              children={STRINGS["lbl_distribution2"] || ""}
              children1={STRINGS["msg_distribution_co"] || ""}
            />
            <Column
              className="instructions6"
              layoutGravity={6}
              gravity={0}
              mainAxisAlignment={"start"}
              crossAxisAlignment={"center"}
              width={314}
              isExpanded={0}
              left={2}
              right={24}
            >
              <Image
                src="img_arrow_12.svg"
                alt="Arrow"
                className="arrow15"
                layoutGravity={44}
                gravity={0}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={135.78}
                left={152.99}
                right={25.22998}
              />
              <Text
                className="choosebetween"
                layoutGravity={33}
                gravity={3}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={314}
                isExpanded={0}
                left={0}
                right={0}
              >
                {STRINGS["msg_choose_between"] || ""}
              </Text>
            </Column>
          </Stack>
        </Column>
        <Column
          className="group113"
          layoutGravity={10}
          gravity={0}
          mainAxisAlignment={"start"}
          crossAxisAlignment={"start"}
          width={788.1699}
          isExpanded={true}
          left={476}
          right={0}
        >
          <Image
            src="img_catpile.png"
            alt="Catpile"
            className="catpile"
            layoutGravity={33}
            gravity={0}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={376}
            left={0}
            right={412.16992}
          />
          <Row
            className="group112"
            layoutGravity={12}
            gravity={0}
            mainAxisAlignment={"end"}
            crossAxisAlignment={"center"}
            width={788.17}
            isExpanded={0}
            left={0}
            right={0}
          >
            <Image
              src="img_catpile_1.png"
              alt="Catpile"
              className="catpile2"
              layoutGravity={10}
              gravity={0}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={297}
              left={0}
              right={0}
            />
            <Column
              className="instructions7"
              layoutGravity={11}
              gravity={0}
              mainAxisAlignment={"start"}
              crossAxisAlignment={"start"}
              width={390.17}
              isExpanded={true}
              left={22}
              right={0}
            >
              <Row
                className="stretch"
                layoutGravity={33}
                gravity={0}
                mainAxisAlignment={"start"}
                crossAxisAlignment={"center"}
                width={390.17}
                isExpanded={0}
                left={0}
                right={0}
              >
                <Image
                  src="img_arrow_13.svg"
                  alt="Arrow"
                  className="arrow16"
                  layoutGravity={10}
                  gravity={0}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={42.17}
                  left={0}
                  right={0}
                />
                <Text
                  className="packeddistribu"
                  layoutGravity={11}
                  gravity={1}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={290}
                  isExpanded={true}
                  left={27}
                  right={0}
                >
                  {STRINGS["msg_packed_distribu"] || ""}
                </Text>
              </Row>
              <Row
                className="stretch2"
                layoutGravity={33}
                gravity={0}
                mainAxisAlignment={"start"}
                crossAxisAlignment={"center"}
                width={390.17}
                isExpanded={0}
                left={0}
                right={0}
              >
                <Image
                  src="img_arrow_13.svg"
                  alt="Arrow"
                  className="arrow17"
                  layoutGravity={10}
                  gravity={0}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={42.17}
                  left={0}
                  right={0}
                />
                <Text
                  className="spacebetweend"
                  layoutGravity={11}
                  gravity={1}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={321}
                  isExpanded={true}
                  left={27}
                  right={0}
                >
                  {STRINGS["msg_space_between_d"] || ""}
                </Text>
              </Row>
            </Column>
          </Row>
        </Column>
      </Row>
    </Column>
  );
};

export default DistributionPage;
