import React from "react";
import { STRINGS } from "../../constants/string";
import { Column } from "../../components/Column";
import { Row } from "../../components/Row";
import { Text } from "../../components/Text";
import { Stack } from "../../components/Stack";
import { Image } from "../../components/Image";
import { Line } from "../../components/Line";

const WelcomePage = () => {
  return (
    <Column
      className="welcome"
      layoutGravity={0}
      gravity={0}
      mainAxisAlignment={"start"}
      crossAxisAlignment={"start"}
      width={1920}
      isExpanded={0}
      left={0}
      right={0}
    >
      <Row
        className="copy2"
        layoutGravity={33}
        gravity={0}
        mainAxisAlignment={"end"}
        crossAxisAlignment={"center"}
        width={1920}
        isExpanded={0}
        left={0}
        right={0}
      >
        <Column
          className="copy3"
          layoutGravity={10}
          gravity={0}
          mainAxisAlignment={"start"}
          crossAxisAlignment={"start"}
          width={816}
          isExpanded={true}
          left={0}
          right={0}
        >
          <Text
            className="welcometoauto"
            layoutGravity={33}
            gravity={4}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={816}
            isExpanded={0}
            left={0}
            right={0}
          >
            {STRINGS["msg_welcome_to_auto"] || ""}
          </Text>
          <Text
            className="thisplayground"
            layoutGravity={33}
            gravity={1}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={755}
            isExpanded={0}
            left={0}
            right={61}
          >
            {STRINGS["msg_this_playground"] || ""}
          </Text>
        </Column>
        <Column
          className="illustration"
          layoutGravity={10}
          gravity={0}
          mainAxisAlignment={"start"}
          crossAxisAlignment={"center"}
          width={711.62}
          isExpanded={0}
          left={112}
          right={0}
        >
          <Column
            className="group64"
            layoutGravity={33}
            gravity={0}
            mainAxisAlignment={"start"}
            crossAxisAlignment={"start"}
            width={711.62}
            isExpanded={0}
            left={0}
            right={0}
          >
            <Row
              className="group63"
              layoutGravity={33}
              gravity={0}
              mainAxisAlignment={"end"}
              crossAxisAlignment={"center"}
              width={711.62}
              isExpanded={0}
              left={0}
              right={0}
            >
              <Stack
                className="group1843"
                layoutGravity={10}
                gravity={0}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={141.49}
                isExpanded={0}
                left={0}
                right={0}
              >
                <Image
                  src="img_rectangle471.svg"
                  alt="Rectangle471"
                  className="rectangle471"
                  layoutGravity={9}
                  gravity={0}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={125.01}
                  left={7.7700195}
                  right={8.709961}
                />
                <Row
                  className="group50"
                  layoutGravity={4}
                  gravity={0}
                  mainAxisAlignment={"start"}
                  crossAxisAlignment={"start"}
                  width={141.49}
                  isExpanded={0}
                  left={0}
                  right={0}
                >
                  <Column
                    className="rectangle472"
                    layoutGravity={10}
                    gravity={0}
                    mainAxisAlignment={"start"}
                    crossAxisAlignment={"start"}
                    width={101.65991}
                    isExpanded={true}
                    left={0}
                    right={0}
                  >
                    <Row
                      className="group57"
                      layoutGravity={12}
                      gravity={0}
                      mainAxisAlignment={"start"}
                      crossAxisAlignment={"center"}
                      width={101.66}
                      isExpanded={0}
                      left={0}
                      right={0}
                    >
                      <Image
                        src="img_group1833.svg"
                        alt="Group1833"
                        className="group1833"
                        layoutGravity={10}
                        gravity={0}
                        mainAxisAlignment={""}
                        crossAxisAlignment={""}
                        width={15.11}
                        left={0}
                        right={0}
                      />
                      <Column
                        className="group56"
                        layoutGravity={10}
                        gravity={0}
                        mainAxisAlignment={"start"}
                        crossAxisAlignment={"center"}
                        width={59.069946}
                        isExpanded={true}
                        left={27.47998}
                        right={0.00012207031}
                      >
                        <Text
                          className="go"
                          layoutGravity={12}
                          gravity={3}
                          mainAxisAlignment={""}
                          crossAxisAlignment={""}
                          width={59.07}
                          isExpanded={0}
                          left={0}
                          right={0}
                        >
                          {STRINGS["lbl_go"] || ""}
                        </Text>
                        <Line
                          className="vector80"
                          layoutGravity={12}
                          gravity={0}
                          isExpanded={0}
                          left={27.310059}
                          right={27.639893}
                          mainAxisAlignment={""}
                          crossAxisAlignment={""}
                          width={4.12}
                        />
                      </Column>
                    </Row>
                  </Column>
                  <Image
                    src="img_group1833.svg"
                    alt="Group1834"
                    className="group1834"
                    layoutGravity={10}
                    gravity={0}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={15.11}
                    left={10}
                    right={0}
                  />
                </Row>
              </Stack>
              <Column
                className="group62"
                layoutGravity={11}
                gravity={0}
                mainAxisAlignment={"start"}
                crossAxisAlignment={"center"}
                width={440.95996}
                isExpanded={true}
                left={70.160034}
                right={0}
              >
                <Column
                  className="group1838"
                  layoutGravity={44}
                  gravity={0}
                  mainAxisAlignment={"start"}
                  crossAxisAlignment={"center"}
                  width={185.5}
                  isExpanded={0}
                  left={157.34998}
                  right={98.109985}
                >
                  <Column
                    className="rectangle4722"
                    layoutGravity={33}
                    gravity={0}
                    mainAxisAlignment={"start"}
                    crossAxisAlignment={"start"}
                    width={141.48999}
                    isExpanded={0}
                    left={0}
                    right={44.01001}
                  >
                    <Row
                      className="group55"
                      layoutGravity={12}
                      gravity={0}
                      mainAxisAlignment={"start"}
                      crossAxisAlignment={"start"}
                      width={141.49}
                      isExpanded={0}
                      left={0}
                      right={0}
                    >
                      <Row
                        className="ellipse131"
                        layoutGravity={11}
                        gravity={0}
                        mainAxisAlignment={"start"}
                        crossAxisAlignment={"center"}
                        width={101.65}
                        isExpanded={true}
                        left={0}
                        right={0}
                      >
                        <Image
                          src="img_group1833_1.svg"
                          alt="Group1833"
                          className="group18332"
                          layoutGravity={11}
                          gravity={0}
                          mainAxisAlignment={""}
                          crossAxisAlignment={""}
                          width={15.11}
                          left={0}
                          right={0}
                        />
                        <Text
                          className="go2"
                          layoutGravity={10}
                          gravity={3}
                          mainAxisAlignment={""}
                          crossAxisAlignment={""}
                          width={59.07}
                          isExpanded={true}
                          left={27.46997}
                          right={0.00012207031}
                        >
                          {STRINGS["lbl_go"] || ""}
                        </Text>
                      </Row>
                      <Image
                        src="img_group1834.svg"
                        alt="Group1834"
                        className="group18342"
                        layoutGravity={11}
                        gravity={0}
                        mainAxisAlignment={""}
                        crossAxisAlignment={""}
                        width={15.11}
                        left={10}
                        right={0}
                      />
                    </Row>
                  </Column>
                  <Image
                    src="img_vector80.svg"
                    alt="Vector80"
                    className="vector802"
                    layoutGravity={44}
                    gravity={0}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={40.8}
                    left={144.69995}
                    right={0}
                  />
                </Column>
                <Stack
                  className="rectangle4723"
                  layoutGravity={12}
                  gravity={0}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={440.96}
                  isExpanded={0}
                  left={0}
                  right={0}
                >
                  <Stack
                    className="group58"
                    layoutGravity={9}
                    gravity={0}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={440.96997}
                    isExpanded={0}
                    left={0}
                    right={0}
                  >
                    <Stack
                      className="group68"
                      layoutGravity={9}
                      gravity={0}
                      mainAxisAlignment={""}
                      crossAxisAlignment={""}
                      width={431.36}
                      isExpanded={0}
                      left={0}
                      right={9.609985}
                    >
                      <div
                        className="rectangle4712"
                        layoutGravity={9}
                        gravity={0}
                        width={423.11}
                        mainAxisAlignment={""}
                        crossAxisAlignment={""}
                        isExpanded={0}
                        type="View"
                      ></div>
                      <Image
                        src="img_group1833_2.svg"
                        alt="Group1833"
                        className="group18333"
                        layoutGravity={1}
                        gravity={0}
                        mainAxisAlignment={""}
                        crossAxisAlignment={""}
                        width={15.11}
                        left={0}
                        right={416.25}
                      />
                    </Stack>
                    <Image
                      src="img_group1834_1.svg"
                      alt="Group1834"
                      className="group18343"
                      layoutGravity={5}
                      gravity={0}
                      mainAxisAlignment={""}
                      crossAxisAlignment={""}
                      width={15.11}
                      left={425.86}
                      right={0}
                    />
                    <Line
                      className="vector803"
                      layoutGravity={8}
                      gravity={0}
                      isExpanded={0}
                      left={221.16992}
                      right={215.68005}
                      mainAxisAlignment={""}
                      crossAxisAlignment={""}
                      width={4.12}
                    />
                  </Stack>
                  <Text
                    className="gogogo"
                    layoutGravity={9}
                    gravity={3}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={59.07}
                    isExpanded={0}
                    left={190.94995}
                    right={190.94006}
                  >
                    {STRINGS["lbl_go_go_go"] || ""}
                  </Text>
                </Stack>
              </Column>
            </Row>
            <Stack
              className="group1839"
              layoutGravity={33}
              gravity={0}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={399.42}
              isExpanded={0}
              left={0}
              right={312.19995}
            >
              <Image
                src="img_rectangle471_1.svg"
                alt="Rectangle471"
                className="rectangle4713"
                layoutGravity={4}
                gravity={0}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={329.91}
                left={8.23999}
                right={61.27002}
              />
              <Stack
                className="group61"
                layoutGravity={1}
                gravity={0}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={399.42}
                isExpanded={0}
                left={0}
                right={0}
              >
                <Stack
                  className="group5"
                  layoutGravity={1}
                  gravity={0}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={342.28003}
                  isExpanded={0}
                  left={0}
                  right={57.140015}
                >
                  <Stack
                    className="group59"
                    layoutGravity={1}
                    gravity={0}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={342.28003}
                    isExpanded={0}
                    left={0}
                    right={0}
                  >
                    <Image
                      src="img_rectangle472.svg"
                      alt="Rectangle472"
                      className="rectangle4724"
                      layoutGravity={9}
                      gravity={0}
                      mainAxisAlignment={""}
                      crossAxisAlignment={""}
                      width={336.78}
                      left={5.5}
                      right={0}
                    />
                    <Image
                      src="img_group1833_3.svg"
                      alt="Group1833"
                      className="group18334"
                      layoutGravity={1}
                      gravity={0}
                      mainAxisAlignment={""}
                      crossAxisAlignment={""}
                      width={15.11}
                      left={0}
                      right={327.17004}
                    />
                  </Stack>
                  <Text
                    className="go3"
                    layoutGravity={9}
                    gravity={3}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={59.07}
                    isExpanded={0}
                    left={144.45996}
                    right={138.75012}
                  >
                    {STRINGS["lbl_go"] || ""}
                  </Text>
                </Stack>
                <Stack
                  className="group60"
                  layoutGravity={2}
                  gravity={0}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={65.46}
                  isExpanded={0}
                  left={333.95996}
                  right={0.00012207031}
                >
                  <Image
                    src="img_group1833_3.svg"
                    alt="Group1834"
                    className="group18344"
                    layoutGravity={1}
                    gravity={0}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={15.11}
                    left={0}
                    right={50.349976}
                  />
                  <Line
                    className="vector804"
                    layoutGravity={5}
                    gravity={0}
                    isExpanded={0}
                    left={7.76001}
                    right={0}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={57.7}
                  />
                </Stack>
              </Stack>
            </Stack>
          </Column>
          <Stack
            className="group67"
            layoutGravity={44}
            gravity={0}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={655.2699}
            isExpanded={0}
            left={49}
            right={7.3499756}
          >
            <Stack
              className="rectangle4725"
              layoutGravity={1}
              gravity={0}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={597.57007}
              isExpanded={0}
              left={0}
              right={57.69995}
            >
              <Stack
                className="group65"
                layoutGravity={1}
                gravity={0}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={597.57007}
                isExpanded={0}
                left={0}
                right={0}
              >
                <div
                  className="rectangle4714"
                  layoutGravity={9}
                  gravity={0}
                  width={589.33}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  isExpanded={0}
                  type="View"
                ></div>
                <Image
                  src="img_group1833_4.svg"
                  alt="Group1833"
                  className="group18335"
                  layoutGravity={1}
                  gravity={0}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={15.11}
                  left={0}
                  right={582.4601}
                />
              </Stack>
              <Text
                className="gooooooo"
                layoutGravity={9}
                gravity={1}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={234.91}
                isExpanded={0}
                left={182.70996}
                right={179.95007}
              >
                {STRINGS["lbl_gooooooo"] || ""}
              </Text>
            </Stack>
            <Stack
              className="group66"
              layoutGravity={2}
              gravity={0}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={63.2}
              isExpanded={0}
              left={592.06995}
              right={0.00012207031}
            >
              <Image
                src="img_group1834_2.svg"
                alt="Group1834"
                className="group18345"
                layoutGravity={1}
                gravity={0}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={15.11}
                left={0}
                right={48.089966}
              />
              <Line
                className="vector805"
                layoutGravity={5}
                gravity={0}
                isExpanded={0}
                left={5.5}
                right={0}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={57.7}
              />
            </Stack>
          </Stack>
        </Column>
      </Row>
    </Column>
  );
};

export default WelcomePage;
