import React from "react";
import { STRINGS } from "../../constants/string";
import { Column } from "../../components/Column";
import { Row } from "../../components/Row";
import { Text } from "../../components/Text";
import { Stack } from "../../components/Stack";
import { Image } from "../../components/Image";
import { Line } from "../../components/Line";

const AlignmentControlsPage = () => {
  return (
    <Column
      className="alignmentcontr"
      layoutGravity={0}
      gravity={0}
      mainAxisAlignment={"start"}
      crossAxisAlignment={"start"}
      width={1920}
      isExpanded={0}
      left={0}
      right={0}
    >
      <Row
        className="group150"
        layoutGravity={33}
        gravity={0}
        mainAxisAlignment={"start"}
        crossAxisAlignment={"center"}
        width={1920}
        isExpanded={0}
        left={0}
        right={0}
      >
        <Column
          className="copy26"
          layoutGravity={11}
          gravity={0}
          mainAxisAlignment={"center"}
          crossAxisAlignment={"center"}
          width={484}
          isExpanded={0}
          left={0}
          right={0}
        >
          <Text
            className="alignmentcontr2"
            layoutGravity={12}
            gravity={1}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={340}
            isExpanded={0}
            left={0}
            right={0}
          >
            {STRINGS["msg_alignment_contr"] || ""}
          </Text>
          <Text
            className="alignmentisno"
            layoutGravity={12}
            gravity={1}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={340}
            isExpanded={0}
            left={0}
            right={0}
          >
            {STRINGS["msg_alignment_is_no"] || ""}
          </Text>
          <Column
            className="steps6"
            layoutGravity={12}
            gravity={0}
            mainAxisAlignment={"start"}
            crossAxisAlignment={"start"}
            width={340}
            isExpanded={0}
            left={0}
            right={0}
          >
            <Row
              className="step18"
              layoutGravity={33}
              gravity={0}
              mainAxisAlignment={"start"}
              crossAxisAlignment={"start"}
              width={340}
              isExpanded={0}
              left={0}
              right={0}
            >
              <Column
                className="bullet19"
                layoutGravity={11}
                gravity={0}
                mainAxisAlignment={"start"}
                crossAxisAlignment={"start"}
                width={42.67}
                isExpanded={0}
                left={0}
                right={0}
              >
                <Text
                  className="b119"
                  layoutGravity={33}
                  gravity={9}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={42.67}
                  isExpanded={0}
                  left={0}
                  right={0}
                >
                  {STRINGS["lbl_1"] || ""}
                </Text>
              </Column>
              <div
                className="group153"
                layoutGravity={11}
                gravity={0}
                width={276}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                isExpanded={true}
                type="HorizontalScroll"
              >
                <Column
                  className="listitem6"
                  layoutGravity={1}
                  gravity={0}
                  mainAxisAlignment={"end"}
                  crossAxisAlignment={"start"}
                  width={276}
                  isExpanded={0}
                  left={0}
                  right={0}
                >
                  <Text
                    className="selectthefram"
                    layoutGravity={12}
                    gravity={1}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={286.67}
                    isExpanded={0}
                    left={0}
                    right={0}
                  >
                    {STRINGS["msg_select_the_fram"] || ""}
                  </Text>
                  <Stack
                    className="group1912"
                    layoutGravity={33}
                    gravity={0}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={239}
                    isExpanded={0}
                    left={0}
                    right={37}
                  >
                    <Image
                      src="img_image26.png"
                      alt="image26"
                      className="image26"
                      layoutGravity={1}
                      gravity={0}
                      mainAxisAlignment={""}
                      crossAxisAlignment={""}
                      width={239}
                      left={0}
                      right={0}
                    />
                    <Image
                      src="img_image27.png"
                      alt="image27"
                      className="image27"
                      layoutGravity={5}
                      gravity={0}
                      mainAxisAlignment={""}
                      crossAxisAlignment={""}
                      width={22}
                      left={137}
                      right={80}
                    />
                  </Stack>
                </Column>
              </div>
            </Row>
            <Row
              className="step27"
              layoutGravity={33}
              gravity={0}
              mainAxisAlignment={"start"}
              crossAxisAlignment={"start"}
              width={340}
              isExpanded={0}
              left={0}
              right={0}
            >
              <Column
                className="bullet20"
                layoutGravity={11}
                gravity={0}
                mainAxisAlignment={"start"}
                crossAxisAlignment={"start"}
                width={42.67}
                isExpanded={0}
                left={0}
                right={0}
              >
                <Text
                  className="b28"
                  layoutGravity={33}
                  gravity={9}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={42.67}
                  isExpanded={0}
                  left={0}
                  right={0}
                >
                  {STRINGS["lbl_2"] || ""}
                </Text>
              </Column>
              <div
                className="group154"
                layoutGravity={11}
                gravity={0}
                width={276}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                isExpanded={true}
                type="HorizontalScroll"
              >
                <Column
                  className="listitem7"
                  layoutGravity={1}
                  gravity={0}
                  mainAxisAlignment={"end"}
                  crossAxisAlignment={"start"}
                  width={276}
                  isExpanded={0}
                  left={0}
                  right={0}
                >
                  <Text
                    className="nextchangeth"
                    layoutGravity={12}
                    gravity={1}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={286.67}
                    isExpanded={0}
                    left={0}
                    right={0}
                  >
                    {STRINGS["msg_next_change_th"] || ""}
                  </Text>
                  <Image
                    src="img_image28.png"
                    alt="image28"
                    className="image28"
                    layoutGravity={33}
                    gravity={0}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={168}
                    left={0}
                    right={108}
                  />
                </Column>
              </div>
            </Row>
          </Column>
        </Column>
        <Column
          className="group149"
          layoutGravity={10}
          gravity={0}
          mainAxisAlignment={"start"}
          crossAxisAlignment={"start"}
          width={1227}
          isExpanded={true}
          left={105}
          right={0}
        >
          <Column
            className="title"
            layoutGravity={33}
            gravity={0}
            mainAxisAlignment={"start"}
            crossAxisAlignment={"start"}
            width={1227}
            isExpanded={0}
            left={0}
            right={0}
          >
            <Stack
              className="group152"
              layoutGravity={33}
              gravity={0}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={1227}
              isExpanded={0}
              left={0}
              right={0}
            >
              <Row
                className="container4"
                layoutGravity={4}
                gravity={0}
                mainAxisAlignment={"center"}
                crossAxisAlignment={"center"}
                width={1227}
                isExpanded={0}
                left={0}
                right={0}
              >
                <Column
                  className="logo"
                  layoutGravity={10}
                  gravity={0}
                  mainAxisAlignment={"start"}
                  crossAxisAlignment={"start"}
                  width={146}
                  isExpanded={0}
                  left={0}
                  right={0}
                >
                  <Image
                    src="img_logo.svg"
                    alt="logo"
                    className="logo2"
                    layoutGravity={33}
                    gravity={0}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={133}
                    left={3}
                    right={10}
                  />
                  <Text
                    className="widgco3"
                    layoutGravity={33}
                    gravity={9}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={146}
                    isExpanded={0}
                    left={0}
                    right={0}
                  >
                    {STRINGS["lbl_widgco"] || ""}
                  </Text>
                </Column>
                <Column
                  className="logo3"
                  layoutGravity={10}
                  gravity={0}
                  mainAxisAlignment={"start"}
                  crossAxisAlignment={"center"}
                  width={133}
                  isExpanded={0}
                  left={50}
                  right={0}
                >
                  <Column
                    className="ellipse39"
                    layoutGravity={33}
                    gravity={0}
                    mainAxisAlignment={"start"}
                    crossAxisAlignment={"center"}
                    width={133}
                    isExpanded={0}
                    left={0}
                    right={0}
                  >
                    <Column
                      className="rectangle"
                      layoutGravity={12}
                      gravity={0}
                      mainAxisAlignment={"start"}
                      crossAxisAlignment={"start"}
                      width={67.47}
                      isExpanded={0}
                      left={0}
                      right={0.000030517578}
                    >
                      <Column
                        className="group"
                        layoutGravity={33}
                        gravity={0}
                        mainAxisAlignment={"start"}
                        crossAxisAlignment={"start"}
                        width={67.47}
                        isExpanded={0}
                        left={0}
                        right={0}
                      >
                        <Column
                          className="group146"
                          layoutGravity={12}
                          gravity={0}
                          mainAxisAlignment={"start"}
                          crossAxisAlignment={"center"}
                          width={67.46997}
                          isExpanded={0}
                          left={0}
                          right={0}
                        >
                          <Stack
                            className="group145"
                            layoutGravity={12}
                            gravity={0}
                            mainAxisAlignment={""}
                            crossAxisAlignment={""}
                            width={67.47}
                            isExpanded={0}
                            left={0}
                            right={0}
                          >
                            <Image
                              src="img_ellipse.svg"
                              alt="Ellipse"
                              className="ellipse"
                              layoutGravity={4}
                              gravity={0}
                              mainAxisAlignment={""}
                              crossAxisAlignment={""}
                              width={35.85}
                              left={0}
                              right={31.619995}
                            />
                            <Image
                              src="img_ellipse_1.svg"
                              alt="Ellipse"
                              className="ellipse2"
                              layoutGravity={4}
                              gravity={0}
                              mainAxisAlignment={""}
                              crossAxisAlignment={""}
                              width={29.36}
                              left={0}
                              right={38.109985}
                            />
                            <Stack
                              className="group151"
                              layoutGravity={4}
                              gravity={0}
                              mainAxisAlignment={""}
                              crossAxisAlignment={""}
                              width={43.049988}
                              isExpanded={0}
                              left={0}
                              right={24.419983}
                            >
                              <Image
                                src="img_ellipse_2.svg"
                                alt="Ellipse"
                                className="ellipse36"
                                layoutGravity={9}
                                gravity={0}
                                mainAxisAlignment={""}
                                crossAxisAlignment={""}
                                width={43.05}
                                left={0}
                                right={0}
                              />
                              <Line
                                className="line4"
                                layoutGravity={6}
                                gravity={0}
                                isExpanded={0}
                                left={0}
                                right={15.320007}
                                mainAxisAlignment={""}
                                crossAxisAlignment={""}
                                width={27.73}
                              />
                            </Stack>
                            <Image
                              src="img_vector.svg"
                              alt="Vector"
                              className="vector"
                              layoutGravity={6}
                              gravity={0}
                              mainAxisAlignment={""}
                              crossAxisAlignment={""}
                              width={67.47}
                              left={0}
                              right={0}
                            />
                          </Stack>
                          <div
                            className="ellipse22"
                            layoutGravity={44}
                            gravity={0}
                            width={9.74}
                            mainAxisAlignment={""}
                            crossAxisAlignment={""}
                            isExpanded={0}
                            type="View"
                          ></div>
                        </Column>
                      </Column>
                    </Column>
                  </Column>
                  <Text
                    className="leicht"
                    layoutGravity={12}
                    gravity={9}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={116}
                    isExpanded={0}
                    left={8}
                    right={9}
                  >
                    {STRINGS["lbl_leicht"] || ""}
                  </Text>
                </Column>
                <Column
                  className="logo4"
                  layoutGravity={10}
                  gravity={0}
                  mainAxisAlignment={"start"}
                  crossAxisAlignment={"center"}
                  width={209}
                  isExpanded={true}
                  left={50}
                  right={0}
                >
                  <Image
                    src="img_logo_1.svg"
                    alt="logo"
                    className="logo5"
                    layoutGravity={12}
                    gravity={0}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={133}
                    left={38}
                    right={38}
                  />
                  <Text
                    className="spacecorp"
                    layoutGravity={33}
                    gravity={9}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={209}
                    isExpanded={0}
                    left={0}
                    right={0}
                  >
                    {STRINGS["lbl_spacecorp"] || ""}
                  </Text>
                </Column>
              </Row>
              <Text
                className="ourpartners"
                layoutGravity={3}
                gravity={1}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={302}
                isExpanded={0}
                left={463}
                right={462}
              >
                {STRINGS["lbl_our_partners"] || ""}
              </Text>
            </Stack>
          </Column>
          <Row
            className="group148"
            layoutGravity={33}
            gravity={0}
            mainAxisAlignment={"end"}
            crossAxisAlignment={"center"}
            width={1227}
            isExpanded={0}
            left={0}
            right={0}
          >
            <Column
              className="logo6"
              layoutGravity={11}
              gravity={0}
              mainAxisAlignment={"start"}
              crossAxisAlignment={"center"}
              width={133}
              isExpanded={0}
              left={0}
              right={0}
            >
              <Image
                src="img_logo_2.svg"
                alt="logo"
                className="logo7"
                layoutGravity={33}
                gravity={0}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={133}
                left={0}
                right={0}
              />
              <Text
                className="cargo"
                layoutGravity={12}
                gravity={9}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={120}
                isExpanded={0}
                left={6}
                right={7}
              >
                {STRINGS["lbl_cargo"] || ""}
              </Text>
            </Column>
            <Row
              className="group147"
              layoutGravity={10}
              gravity={0}
              mainAxisAlignment={"start"}
              crossAxisAlignment={"center"}
              width={836.86}
              isExpanded={true}
              left={34.140015}
              right={0}
            >
              <Image
                src="img_arrow_23.svg"
                alt="Arrow"
                className="arrow29"
                layoutGravity={10}
                gravity={0}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={173.86}
                left={0}
                right={0}
              />
              <Text
                className="afteryouvese"
                layoutGravity={10}
                gravity={1}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={345}
                isExpanded={true}
                left={37}
                right={0}
              >
                {STRINGS["msg_after_you_ve_se"] || ""}
              </Text>
            </Row>
          </Row>
        </Column>
      </Row>
    </Column>
  );
};

export default AlignmentControlsPage;
