import React from "react";
import { STRINGS } from "../../constants/string";
import { Row } from "../../components/Row";
import { Column } from "../../components/Column";
import { Text } from "../../components/Text";
import { List } from "../../components/List";
import { Stack } from "../../components/Stack";
import { Image } from "../../components/Image";
import { PuttingitalltogetherFrame31 } from "../../components/PuttingitalltogetherFrame31";
import { Line } from "../../components/Line";

const PuttingitalltogetherPage = () => {
  return (
    <Row
      className="puttingitall"
      layoutGravity={0}
      gravity={0}
      mainAxisAlignment={"start"}
      crossAxisAlignment={"center"}
      width={1920}
      isExpanded={0}
      left={0}
      right={0}
    >
      <Column
        className="copy19"
        layoutGravity={11}
        gravity={0}
        mainAxisAlignment={"center"}
        crossAxisAlignment={"center"}
        width={484}
        isExpanded={0}
        left={0}
        right={0}
      >
        <Text
          className="puttingitall2"
          layoutGravity={12}
          gravity={1}
          mainAxisAlignment={""}
          crossAxisAlignment={""}
          width={340}
          isExpanded={0}
          left={0}
          right={0}
        >
          {STRINGS["msg_putting_it_all"] || ""}
        </Text>
        <Text
          className="herewevecomb"
          layoutGravity={12}
          gravity={1}
          mainAxisAlignment={""}
          crossAxisAlignment={""}
          width={340}
          isExpanded={0}
          left={0}
          right={0}
        >
          {STRINGS["msg_here_we_ve_comb"] || ""}
        </Text>
        <Column
          className="steps4"
          layoutGravity={12}
          gravity={0}
          mainAxisAlignment={"start"}
          crossAxisAlignment={"start"}
          width={340}
          isExpanded={0}
          left={0}
          right={0}
        >
          <Row
            className="step15"
            layoutGravity={33}
            gravity={0}
            mainAxisAlignment={"start"}
            crossAxisAlignment={"start"}
            width={340}
            isExpanded={0}
            left={0}
            right={0}
          >
            <Column
              className="bullet12"
              layoutGravity={11}
              gravity={0}
              mainAxisAlignment={"start"}
              crossAxisAlignment={"start"}
              width={42.67}
              isExpanded={0}
              left={0}
              right={0}
            >
              <Text
                className="b111"
                layoutGravity={33}
                gravity={9}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={42.67}
                isExpanded={0}
                left={0}
                right={0}
              >
                {STRINGS["lbl_1"] || ""}
              </Text>
            </Column>
            <Text
              className="addanimageto"
              layoutGravity={10}
              gravity={1}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={276}
              isExpanded={true}
              left={21.330002}
              right={0}
            >
              {STRINGS["msg_add_an_image_to"] || ""}
            </Text>
          </Row>
          <List
            className="group135"
            orientation="vertical"
            layoutGravity={33}
            gravity={0}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={340}
          >
            <Row
              className="step25"
              layoutGravity={1}
              gravity={0}
              mainAxisAlignment={"start"}
              crossAxisAlignment={"start"}
              width={340}
              isExpanded={0}
              left={0}
              right={0}
            >
              <Column
                className="bullet13"
                layoutGravity={10}
                gravity={0}
                mainAxisAlignment={"start"}
                crossAxisAlignment={"start"}
                width={42.67}
                isExpanded={0}
                left={0}
                right={0}
              >
                <Text
                  className="b26"
                  layoutGravity={33}
                  gravity={9}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={42.67}
                  isExpanded={0}
                  left={0}
                  right={0}
                >
                  {STRINGS["lbl_2"] || ""}
                </Text>
              </Column>
              <Text
                className="movethefourth"
                layoutGravity={11}
                gravity={1}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={276}
                isExpanded={true}
                left={21.330002}
                right={0}
              >
                {STRINGS["msg_move_the_fourth"] || ""}
              </Text>
            </Row>
            <Row
              className="step34"
              layoutGravity={4}
              gravity={0}
              mainAxisAlignment={"start"}
              crossAxisAlignment={"start"}
              width={340}
              isExpanded={0}
              left={0}
              right={0}
            >
              <Column
                className="bullet14"
                layoutGravity={10}
                gravity={0}
                mainAxisAlignment={"start"}
                crossAxisAlignment={"start"}
                width={42.67}
                isExpanded={0}
                left={0}
                right={0}
              >
                <Text
                  className="b35"
                  layoutGravity={33}
                  gravity={9}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={42.67}
                  isExpanded={0}
                  left={0}
                  right={0}
                >
                  {STRINGS["lbl_3"] || ""}
                </Text>
              </Column>
              <Text
                className="changethewidt"
                layoutGravity={11}
                gravity={1}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={276}
                isExpanded={true}
                left={21.330002}
                right={0}
              >
                {STRINGS["msg_change_the_widt"] || ""}
              </Text>
            </Row>
            <Row
              className="step4"
              layoutGravity={6}
              gravity={0}
              mainAxisAlignment={"start"}
              crossAxisAlignment={"start"}
              width={340}
              isExpanded={0}
              left={0}
              right={0}
            >
              <Column
                className="bullet15"
                layoutGravity={10}
                gravity={0}
                mainAxisAlignment={"start"}
                crossAxisAlignment={"start"}
                width={42.67}
                isExpanded={0}
                left={0}
                right={0}
              >
                <Text
                  className="b42"
                  layoutGravity={33}
                  gravity={9}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={42.67}
                  isExpanded={0}
                  left={0}
                  right={0}
                >
                  {STRINGS["lbl_4"] || ""}
                </Text>
              </Column>
              <Text
                className="changethedist"
                layoutGravity={11}
                gravity={1}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={276}
                isExpanded={true}
                left={21.330002}
                right={0}
              >
                {STRINGS["msg_change_the_dist"] || ""}
              </Text>
            </Row>
          </List>
        </Column>
      </Column>
      <Row
        className="group132"
        layoutGravity={10}
        gravity={0}
        mainAxisAlignment={"start"}
        crossAxisAlignment={"center"}
        width={1340}
        isExpanded={true}
        left={96}
        right={0}
      >
        <Text
          className="horizontalauto"
          layoutGravity={22}
          gravity={2}
          mainAxisAlignment={""}
          crossAxisAlignment={""}
          width={353}
          isExpanded={0}
          left={0}
          right={0}
        >
          {STRINGS["msg_horizontal_aut"] || ""}
        </Text>
        <Stack
          className="group134"
          layoutGravity={10}
          gravity={0}
          mainAxisAlignment={""}
          crossAxisAlignment={""}
          width={826}
          isExpanded={true}
          left={27}
          right={0}
        >
          <Image
            src="img_arrow_18.svg"
            alt="Arrow"
            className="arrow24"
            layoutGravity={6}
            gravity={0}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={65.74}
            left={0}
            right={760.26}
          />
          <Image
            src="img_arrow_19.svg"
            alt="Arrow"
            className="arrow25"
            layoutGravity={5}
            gravity={0}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={95.24}
            left={397}
            right={333.76}
          />
          <Column
            className="mews"
            layoutGravity={1}
            gravity={0}
            mainAxisAlignment={"end"}
            crossAxisAlignment={"start"}
            width={375}
            isExpanded={0}
            left={55}
            right={396}
          >
            <Column
              className="mew"
              layoutGravity={33}
              gravity={0}
              mainAxisAlignment={"start"}
              crossAxisAlignment={"center"}
              width={375}
              isExpanded={0}
              left={0}
              right={0}
            >
              <div
                className="group137"
                layoutGravity={44}
                gravity={0}
                width={279}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                isExpanded={0}
                type="HorizontalScroll"
              >
                <Column
                  className="group126"
                  layoutGravity={1}
                  gravity={0}
                  mainAxisAlignment={"start"}
                  crossAxisAlignment={"center"}
                  width={279}
                  isExpanded={0}
                  left={0}
                  right={0}
                >
                  <Stack
                    className="group133"
                    layoutGravity={44}
                    gravity={0}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={954}
                    isExpanded={0}
                    left={0}
                    right={0}
                  >
                    <div
                      className="group26"
                      layoutGravity={1}
                      gravity={0}
                      width={954}
                      mainAxisAlignment={""}
                      crossAxisAlignment={""}
                      isExpanded={0}
                      type="AppBar"
                    >
                      <Text
                        className="verticalautola"
                        layoutGravity={0}
                        gravity={1}
                        mainAxisAlignment={""}
                        crossAxisAlignment={""}
                        width={220}
                        isExpanded={0}
                        left={543}
                        right={191}
                      >
                        {STRINGS["msg_vertical_autola"] || ""}
                      </Text>
                      <Image
                        src="img_arrow_20.svg"
                        alt="Arrow"
                        className="arrow26"
                        layoutGravity={0}
                        gravity={0}
                        mainAxisAlignment={""}
                        crossAxisAlignment={""}
                        width={93.27}
                        left={449.99}
                        right={410.74}
                      />
                      <div
                        className="ellipse3"
                        layoutGravity={0}
                        gravity={0}
                        width={48}
                        mainAxisAlignment={""}
                        crossAxisAlignment={""}
                        isExpanded={0}
                        type="CircleImage"
                      ></div>
                      <Row
                        className="namehandle4"
                        layoutGravity={0}
                        gravity={0}
                        mainAxisAlignment={"start"}
                        crossAxisAlignment={"start"}
                        width={279}
                        isExpanded={0}
                        left={300}
                        right={375}
                      >
                        <Text
                          className="alicat"
                          layoutGravity={11}
                          gravity={1}
                          mainAxisAlignment={""}
                          crossAxisAlignment={""}
                          width={52}
                          isExpanded={true}
                          left={0}
                          right={0}
                        >
                          {STRINGS["lbl_ali_cat"] || ""}
                        </Text>
                        <Text
                          className="meowington"
                          layoutGravity={11}
                          gravity={1}
                          mainAxisAlignment={""}
                          crossAxisAlignment={""}
                          width={33}
                          isExpanded={0}
                          left={10}
                          right={0}
                        >
                          {STRINGS["lbl_ali"] || ""}
                        </Text>
                      </Row>
                      <Text
                        className="fillcontainer"
                        layoutGravity={0}
                        gravity={1}
                        mainAxisAlignment={""}
                        crossAxisAlignment={""}
                        width={279}
                        isExpanded={0}
                        left={675}
                        right={0}
                      >
                        {STRINGS["msg_fill_container"] || ""}
                      </Text>
                      <Image
                        src="img_arrow_21.svg"
                        alt="Arrow"
                        className="arrow27"
                        layoutGravity={0}
                        gravity={0}
                        mainAxisAlignment={""}
                        crossAxisAlignment={""}
                        width={95.24}
                        left={572}
                        right={286.76}
                      />
                      <Text
                        className="fixedwidth"
                        layoutGravity={0}
                        gravity={1}
                        mainAxisAlignment={""}
                        crossAxisAlignment={""}
                        width={134}
                        isExpanded={0}
                        left={0}
                        right={820}
                      >
                        {STRINGS["lbl_fixed_width"] || ""}
                      </Text>
                      <Text
                        className="adesignplatfo6"
                        layoutGravity={0}
                        gravity={1}
                        mainAxisAlignment={""}
                        crossAxisAlignment={""}
                        width={279}
                        isExpanded={0}
                        left={300}
                        right={375}
                      >
                        {STRINGS["msg_catnip_got_me_l"] || ""}
                      </Text>
                      <Image
                        src="img_arrow_22.svg"
                        alt="Arrow"
                        className="arrow28"
                        layoutGravity={0}
                        gravity={0}
                        mainAxisAlignment={""}
                        crossAxisAlignment={""}
                        width={95.24}
                        left={134}
                        right={724.76}
                      />
                    </div>
                    <Image
                      src="img_photo_1.png"
                      alt="photo"
                      className="photo10"
                      layoutGravity={6}
                      gravity={0}
                      mainAxisAlignment={""}
                      crossAxisAlignment={""}
                      width={279}
                      left={300}
                      right={375}
                    />
                  </Stack>
                  <Text
                    className="c2m"
                    layoutGravity={33}
                    gravity={1}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={24}
                    isExpanded={0}
                    left={0}
                    right={255}
                  >
                    {STRINGS["lbl_2m"] || ""}
                  </Text>
                  <PuttingitalltogetherFrame31 />
                </Column>
              </div>
              <Line
                className="line6"
                layoutGravity={33}
                gravity={0}
                isExpanded={0}
                left={0}
                right={0}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={375}
              />
            </Column>
            <List
              className="group136"
              orientation="vertical"
              layoutGravity={33}
              gravity={0}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={375}
            >
              <Column
                className="group128"
                layoutGravity={1}
                gravity={0}
                mainAxisAlignment={"start"}
                crossAxisAlignment={"start"}
                width={375}
                isExpanded={0}
                left={0}
                right={0}
              >
                <Row
                  className="group127"
                  layoutGravity={33}
                  gravity={0}
                  mainAxisAlignment={"start"}
                  crossAxisAlignment={"start"}
                  width={375}
                  isExpanded={0}
                  left={0}
                  right={0}
                >
                  <div
                    className="ellipse32"
                    layoutGravity={11}
                    gravity={0}
                    width={48}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    isExpanded={0}
                    type="CircleImage"
                  ></div>
                  <Column
                    className="post5"
                    layoutGravity={11}
                    gravity={0}
                    mainAxisAlignment={"start"}
                    crossAxisAlignment={"start"}
                    width={279}
                    isExpanded={true}
                    left={16}
                    right={0}
                  >
                    <Row
                      className="namehandle5"
                      layoutGravity={33}
                      gravity={0}
                      mainAxisAlignment={"start"}
                      crossAxisAlignment={"start"}
                      width={279}
                      isExpanded={0}
                      left={0}
                      right={0}
                    >
                      <Text
                        className="veronicat"
                        layoutGravity={11}
                        gravity={1}
                        mainAxisAlignment={""}
                        crossAxisAlignment={""}
                        width={76}
                        isExpanded={0}
                        left={0}
                        right={0}
                      >
                        {STRINGS["lbl_veronicat"] || ""}
                      </Text>
                      <Text
                        className="meowington2"
                        layoutGravity={11}
                        gravity={1}
                        mainAxisAlignment={""}
                        crossAxisAlignment={""}
                        width={77}
                        isExpanded={true}
                        left={4}
                        right={0}
                      >
                        {STRINGS["lbl_kittyvee"] || ""}
                      </Text>
                    </Row>
                    <Text
                      className="adesignplatfo7"
                      layoutGravity={33}
                      gravity={1}
                      mainAxisAlignment={""}
                      crossAxisAlignment={""}
                      width={279}
                      isExpanded={0}
                      left={0}
                      right={0}
                    >
                      {STRINGS["msg_what_was_the_ca"] || ""}
                    </Text>
                    <Text
                      className="c2m2"
                      layoutGravity={33}
                      gravity={1}
                      mainAxisAlignment={""}
                      crossAxisAlignment={""}
                      width={24}
                      isExpanded={0}
                      left={0}
                      right={255}
                    >
                      {STRINGS["lbl_2m"] || ""}
                    </Text>
                    <Row
                      className="frame313"
                      layoutGravity={33}
                      gravity={0}
                      mainAxisAlignment={"start"}
                      crossAxisAlignment={"center"}
                      width={279}
                      isExpanded={0}
                      left={0}
                      right={0}
                    >
                      <Row
                        className="frame323"
                        layoutGravity={10}
                        gravity={0}
                        mainAxisAlignment={"start"}
                        crossAxisAlignment={"start"}
                        width={40}
                        isExpanded={0}
                        left={0}
                        right={0}
                      >
                        <Image
                          src="img_iconcomment_2.svg"
                          alt="IconComment"
                          className="iconcomment10"
                          layoutGravity={11}
                          gravity={0}
                          mainAxisAlignment={""}
                          crossAxisAlignment={""}
                          width={24}
                          left={0}
                          right={0}
                        />
                        <Text
                          className="b113"
                          layoutGravity={11}
                          gravity={1}
                          mainAxisAlignment={""}
                          crossAxisAlignment={""}
                          width={8}
                          isExpanded={true}
                          left={8}
                          right={0}
                        >
                          {STRINGS["lbl_1"] || ""}
                        </Text>
                      </Row>
                      <Row
                        className="frame333"
                        layoutGravity={10}
                        gravity={0}
                        mainAxisAlignment={"start"}
                        crossAxisAlignment={"start"}
                        width={48}
                        isExpanded={0}
                        left={38.329956}
                        right={0}
                      >
                        <Image
                          src="img_iconrepost_1.svg"
                          alt="IconRepost"
                          className="iconrepost7"
                          layoutGravity={11}
                          gravity={0}
                          mainAxisAlignment={""}
                          crossAxisAlignment={""}
                          width={24}
                          left={0}
                          right={0}
                        />
                        <Text
                          className="c117"
                          layoutGravity={11}
                          gravity={1}
                          mainAxisAlignment={""}
                          crossAxisAlignment={""}
                          width={16}
                          isExpanded={true}
                          left={8}
                          right={0}
                        >
                          {STRINGS["lbl_11"] || ""}
                        </Text>
                      </Row>
                      <Row
                        className="frame343"
                        layoutGravity={10}
                        gravity={0}
                        mainAxisAlignment={"start"}
                        crossAxisAlignment={"start"}
                        width={52}
                        isExpanded={true}
                        left={38.340088}
                        right={0}
                      >
                        <Image
                          src="img_iconlike_2.svg"
                          alt="IconLike"
                          className="iconlike10"
                          layoutGravity={11}
                          gravity={0}
                          mainAxisAlignment={""}
                          crossAxisAlignment={""}
                          width={24}
                          left={0}
                          right={0}
                        />
                        <Text
                          className="c677"
                          layoutGravity={11}
                          gravity={1}
                          mainAxisAlignment={""}
                          crossAxisAlignment={""}
                          width={20}
                          isExpanded={true}
                          left={8}
                          right={0}
                        >
                          {STRINGS["lbl_67"] || ""}
                        </Text>
                      </Row>
                      <Image
                        src="img_iconshare_2.svg"
                        alt="IconShare"
                        className="iconshare6"
                        layoutGravity={10}
                        gravity={0}
                        mainAxisAlignment={""}
                        crossAxisAlignment={""}
                        width={24}
                        left={38.329956}
                        right={0}
                      />
                    </Row>
                  </Column>
                </Row>
                <Line
                  className="line7"
                  layoutGravity={33}
                  gravity={0}
                  isExpanded={0}
                  left={0}
                  right={0}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={375}
                />
              </Column>
              <Column
                className="group130"
                layoutGravity={6}
                gravity={0}
                mainAxisAlignment={"end"}
                crossAxisAlignment={"start"}
                width={375}
                isExpanded={0}
                left={0}
                right={0}
              >
                <Row
                  className="group129"
                  layoutGravity={33}
                  gravity={0}
                  mainAxisAlignment={"start"}
                  crossAxisAlignment={"start"}
                  width={375}
                  isExpanded={0}
                  left={0}
                  right={0}
                >
                  <div
                    className="ellipse33"
                    layoutGravity={11}
                    gravity={0}
                    width={48}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    isExpanded={0}
                    type="CircleImage"
                  ></div>
                  <Column
                    className="post6"
                    layoutGravity={11}
                    gravity={0}
                    mainAxisAlignment={"start"}
                    crossAxisAlignment={"start"}
                    width={279}
                    isExpanded={true}
                    left={16}
                    right={0}
                  >
                    <Row
                      className="namehandle6"
                      layoutGravity={33}
                      gravity={0}
                      mainAxisAlignment={"start"}
                      crossAxisAlignment={"start"}
                      width={279}
                      isExpanded={0}
                      left={0}
                      right={0}
                    >
                      <Text
                        className="clawdia"
                        layoutGravity={11}
                        gravity={1}
                        mainAxisAlignment={""}
                        crossAxisAlignment={""}
                        width={63}
                        isExpanded={true}
                        left={0}
                        right={0}
                      >
                        {STRINGS["lbl_clawdia"] || ""}
                      </Text>
                      <Text
                        className="meowington3"
                        layoutGravity={11}
                        gravity={1}
                        mainAxisAlignment={""}
                        crossAxisAlignment={""}
                        width={60}
                        isExpanded={0}
                        left={10}
                        right={0}
                      >
                        {STRINGS["lbl_claws"] || ""}
                      </Text>
                    </Row>
                    <Text
                      className="adesignplatfo8"
                      layoutGravity={33}
                      gravity={1}
                      mainAxisAlignment={""}
                      crossAxisAlignment={""}
                      width={279}
                      isExpanded={0}
                      left={0}
                      right={0}
                    >
                      {STRINGS["msg_what_do_you_cal"] || ""}
                    </Text>
                    <Text
                      className="c2m3"
                      layoutGravity={33}
                      gravity={1}
                      mainAxisAlignment={""}
                      crossAxisAlignment={""}
                      width={24}
                      isExpanded={0}
                      left={0}
                      right={255}
                    >
                      {STRINGS["lbl_2m"] || ""}
                    </Text>
                    <Row
                      className="frame314"
                      layoutGravity={33}
                      gravity={0}
                      mainAxisAlignment={"start"}
                      crossAxisAlignment={"center"}
                      width={279}
                      isExpanded={0}
                      left={0}
                      right={0}
                    >
                      <Row
                        className="frame324"
                        layoutGravity={10}
                        gravity={0}
                        mainAxisAlignment={"start"}
                        crossAxisAlignment={"start"}
                        width={40}
                        isExpanded={0}
                        left={0}
                        right={0}
                      >
                        <Image
                          src="img_iconcomment_2.svg"
                          alt="IconComment"
                          className="iconcomment11"
                          layoutGravity={11}
                          gravity={0}
                          mainAxisAlignment={""}
                          crossAxisAlignment={""}
                          width={24}
                          left={0}
                          right={0}
                        />
                        <Text
                          className="b114"
                          layoutGravity={11}
                          gravity={1}
                          mainAxisAlignment={""}
                          crossAxisAlignment={""}
                          width={8}
                          isExpanded={true}
                          left={8}
                          right={0}
                        >
                          {STRINGS["lbl_1"] || ""}
                        </Text>
                      </Row>
                      <Row
                        className="frame334"
                        layoutGravity={10}
                        gravity={0}
                        mainAxisAlignment={"start"}
                        crossAxisAlignment={"start"}
                        width={48}
                        isExpanded={0}
                        left={38.329956}
                        right={0}
                      >
                        <Image
                          src="img_iconrepost_1.svg"
                          alt="IconRepost"
                          className="iconrepost8"
                          layoutGravity={11}
                          gravity={0}
                          mainAxisAlignment={""}
                          crossAxisAlignment={""}
                          width={24}
                          left={0}
                          right={0}
                        />
                        <Text
                          className="c118"
                          layoutGravity={11}
                          gravity={1}
                          mainAxisAlignment={""}
                          crossAxisAlignment={""}
                          width={16}
                          isExpanded={true}
                          left={8}
                          right={0}
                        >
                          {STRINGS["lbl_11"] || ""}
                        </Text>
                      </Row>
                      <Row
                        className="frame344"
                        layoutGravity={10}
                        gravity={0}
                        mainAxisAlignment={"start"}
                        crossAxisAlignment={"start"}
                        width={52}
                        isExpanded={true}
                        left={38.340088}
                        right={0}
                      >
                        <Image
                          src="img_iconlike_2.svg"
                          alt="IconLike"
                          className="iconlike11"
                          layoutGravity={11}
                          gravity={0}
                          mainAxisAlignment={""}
                          crossAxisAlignment={""}
                          width={24}
                          left={0}
                          right={0}
                        />
                        <Text
                          className="c678"
                          layoutGravity={11}
                          gravity={1}
                          mainAxisAlignment={""}
                          crossAxisAlignment={""}
                          width={20}
                          isExpanded={true}
                          left={8}
                          right={0}
                        >
                          {STRINGS["lbl_67"] || ""}
                        </Text>
                      </Row>
                      <Image
                        src="img_iconshare_2.svg"
                        alt="IconShare"
                        className="iconshare7"
                        layoutGravity={10}
                        gravity={0}
                        mainAxisAlignment={""}
                        crossAxisAlignment={""}
                        width={24}
                        left={38.329956}
                        right={0}
                      />
                    </Row>
                  </Column>
                </Row>
                <Line
                  className="line8"
                  layoutGravity={33}
                  gravity={0}
                  isExpanded={0}
                  left={0}
                  right={0}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={375}
                />
              </Column>
            </List>
            <Stack
              className="mew2"
              layoutGravity={33}
              gravity={0}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={375}
              isExpanded={0}
              left={0}
              right={0}
            >
              <Row
                className="group131"
                layoutGravity={4}
                gravity={0}
                mainAxisAlignment={"start"}
                crossAxisAlignment={"start"}
                width={375}
                isExpanded={0}
                left={0}
                right={0}
              >
                <div
                  className="ellipse34"
                  layoutGravity={11}
                  gravity={0}
                  width={48}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  isExpanded={0}
                  type="CircleImage"
                ></div>
                <Column
                  className="post7"
                  layoutGravity={11}
                  gravity={0}
                  mainAxisAlignment={"start"}
                  crossAxisAlignment={"start"}
                  width={279}
                  isExpanded={true}
                  left={16}
                  right={0}
                >
                  <Row
                    className="namehandle7"
                    layoutGravity={33}
                    gravity={0}
                    mainAxisAlignment={"start"}
                    crossAxisAlignment={"start"}
                    width={279}
                    isExpanded={0}
                    left={0}
                    right={0}
                  >
                    <Text
                      className="catrickswayze"
                      layoutGravity={11}
                      gravity={1}
                      mainAxisAlignment={""}
                      crossAxisAlignment={""}
                      width={122}
                      isExpanded={true}
                      left={0}
                      right={0}
                    >
                      {STRINGS["lbl_catrick_swayze"] || ""}
                    </Text>
                    <Text
                      className="meowington4"
                      layoutGravity={11}
                      gravity={1}
                      mainAxisAlignment={""}
                      crossAxisAlignment={""}
                      width={68}
                      isExpanded={0}
                      left={10}
                      right={0}
                    >
                      {STRINGS["lbl_catrick"] || ""}
                    </Text>
                  </Row>
                  <Text
                    className="adesignplatfo9"
                    layoutGravity={33}
                    gravity={1}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={279}
                    isExpanded={0}
                    left={0}
                    right={0}
                  >
                    {STRINGS["msg_what_do_you_cal2"] || ""}
                  </Text>
                  <Text
                    className="c2m4"
                    layoutGravity={33}
                    gravity={1}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={24}
                    isExpanded={0}
                    left={0}
                    right={255}
                  >
                    {STRINGS["lbl_2m"] || ""}
                  </Text>
                  <PuttingitalltogetherFrame31 />
                </Column>
              </Row>
              <Line
                className="line10"
                layoutGravity={6}
                gravity={0}
                isExpanded={0}
                left={0}
                right={0}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={375}
              />
              <List
                className="navigationbar"
                orientation="horizontal"
                layoutGravity={4}
                gravity={0}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={375}
              >
                <Column
                  className="tabbartab"
                  layoutGravity={0}
                  gravity={0}
                  mainAxisAlignment={"start"}
                  crossAxisAlignment={"center"}
                  width={98.33}
                  isExpanded={0}
                  left={16}
                  right={260.67004}
                >
                  <Image
                    src="img_iconhome.svg"
                    alt="IconHome"
                    className="iconhome"
                    layoutGravity={12}
                    gravity={0}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={32}
                    left={7.000044}
                    right={6.9999123}
                  />
                  <Text
                    className="home"
                    layoutGravity={12}
                    gravity={1}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={46}
                    isExpanded={0}
                    left={0.00004386902}
                    right={-0.00008773804}
                  >
                    {STRINGS["lbl_home"] || ""}
                  </Text>
                </Column>
                <Column
                  className="tabbartab2"
                  layoutGravity={0}
                  gravity={0}
                  mainAxisAlignment={"start"}
                  crossAxisAlignment={"center"}
                  width={98.33}
                  isExpanded={0}
                  left={138.32996}
                  right={138.34009}
                >
                  <Image
                    src="img_iconhome_1.svg"
                    alt="IconHome"
                    className="iconhome2"
                    layoutGravity={12}
                    gravity={0}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={32}
                    left={7.000044}
                    right={6.9999123}
                  />
                  <Text
                    className="alerts"
                    layoutGravity={12}
                    gravity={1}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={46}
                    isExpanded={0}
                    left={0.00004386902}
                    right={-0.00008773804}
                  >
                    {STRINGS["lbl_alerts"] || ""}
                  </Text>
                </Column>
                <Column
                  className="tabbartab3"
                  layoutGravity={0}
                  gravity={0}
                  mainAxisAlignment={"start"}
                  crossAxisAlignment={"center"}
                  width={98.33}
                  isExpanded={0}
                  left={260.67004}
                  right={16}
                >
                  <Image
                    src="img_iconhome_2.svg"
                    alt="IconHome"
                    className="iconhome3"
                    layoutGravity={12}
                    gravity={0}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={32}
                    left={12.999912}
                    right={13.000044}
                  />
                  <Text
                    className="explore"
                    layoutGravity={12}
                    gravity={1}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={58}
                    isExpanded={0}
                    left={-0.00008773804}
                    right={0.00004386902}
                  >
                    {STRINGS["lbl_explore"] || ""}
                  </Text>
                </Column>
              </List>
            </Stack>
            <Row
              className="mew3"
              layoutGravity={33}
              gravity={0}
              mainAxisAlignment={"start"}
              crossAxisAlignment={"start"}
              width={375}
              isExpanded={0}
              left={0}
              right={0}
            >
              <div
                className="ellipse35"
                layoutGravity={11}
                gravity={0}
                width={48}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                isExpanded={0}
                type="CircleImage"
              ></div>
              <Column
                className="post8"
                layoutGravity={10}
                gravity={0}
                mainAxisAlignment={"start"}
                crossAxisAlignment={"start"}
                width={279}
                isExpanded={true}
                left={16}
                right={0}
              >
                <Row
                  className="namehandle8"
                  layoutGravity={33}
                  gravity={0}
                  mainAxisAlignment={"start"}
                  crossAxisAlignment={"start"}
                  width={279}
                  isExpanded={0}
                  left={0}
                  right={0}
                >
                  <Text
                    className="meowington5"
                    layoutGravity={11}
                    gravity={1}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={135}
                    isExpanded={true}
                    left={0}
                    right={0}
                  >
                    {STRINGS["lbl_meowchael_scott"] || ""}
                  </Text>
                  <Text
                    className="meowington6"
                    layoutGravity={11}
                    gravity={1}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={96}
                    isExpanded={0}
                    left={10}
                    right={0}
                  >
                    {STRINGS["lbl_scottscats"] || ""}
                  </Text>
                </Row>
                <Text
                  className="adesignplatfo10"
                  layoutGravity={33}
                  gravity={1}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={279}
                  isExpanded={0}
                  left={0}
                  right={0}
                >
                  {STRINGS["lbl_meow"] || ""}
                </Text>
                <Text
                  className="c2m5"
                  layoutGravity={33}
                  gravity={1}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={24}
                  isExpanded={0}
                  left={0}
                  right={255}
                >
                  {STRINGS["lbl_2m"] || ""}
                </Text>
                <PuttingitalltogetherFrame31 />
              </Column>
            </Row>
          </Column>
          <Text
            className="horizontalauto2"
            layoutGravity={5}
            gravity={1}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={353}
            isExpanded={0}
            left={473}
            right={0}
          >
            {STRINGS["msg_horizontal_auto"] || ""}
          </Text>
        </Stack>
      </Row>
    </Row>
  );
};

export default PuttingitalltogetherPage;
