import React from "react";
import { STRINGS } from "../../constants/string";
import { Column } from "../../components/Column";
import { Row } from "../../components/Row";
import { Text } from "../../components/Text";
import { List } from "../../components/List";
import { Image } from "../../components/Image";

const Resizing2Page = () => {
  return (
    <Column
      className="resizing8"
      layoutGravity={0}
      gravity={0}
      mainAxisAlignment={"start"}
      crossAxisAlignment={"start"}
      width={1920}
      isExpanded={0}
      left={0}
      right={0}
    >
      <Row
        className="group100"
        layoutGravity={33}
        gravity={0}
        mainAxisAlignment={"start"}
        crossAxisAlignment={"center"}
        width={1920}
        isExpanded={0}
        left={0}
        right={0}
      >
        <Column
          className="copy12"
          layoutGravity={11}
          gravity={0}
          mainAxisAlignment={"center"}
          crossAxisAlignment={"center"}
          width={484}
          isExpanded={0}
          left={0}
          right={0}
        >
          <Text
            className="resizing9"
            layoutGravity={12}
            gravity={1}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={340}
            isExpanded={0}
            left={0}
            right={0}
          >
            {STRINGS["lbl_resizing4"] || ""}
          </Text>
          <Text
            className="incontrastth"
            layoutGravity={12}
            gravity={1}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={340}
            isExpanded={0}
            left={0}
            right={0}
          >
            {STRINGS["msg_in_contrast_th"] || ""}
          </Text>
        </Column>
        <Column
          className="group99"
          layoutGravity={10}
          gravity={0}
          mainAxisAlignment={"start"}
          crossAxisAlignment={"start"}
          width={1154}
          isExpanded={true}
          left={142}
          right={0}
        >
          <List
            className="stretchshrin2"
            orientation="horizontal"
            layoutGravity={33}
            gravity={0}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={1154}
          >
            <Column
              className="postcontainer3"
              layoutGravity={4}
              gravity={0}
              mainAxisAlignment={"start"}
              crossAxisAlignment={"start"}
              width={461}
              isExpanded={0}
              left={100}
              right={593}
            >
              <Row
                className="innercontainer4"
                layoutGravity={33}
                gravity={0}
                mainAxisAlignment={"center"}
                crossAxisAlignment={"start"}
                width={461}
                isExpanded={0}
                left={0}
                right={0}
              >
                <Image
                  src="img_avatar_2.svg"
                  alt="Avatar"
                  className="avatar3"
                  layoutGravity={11}
                  gravity={0}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={80}
                  left={0}
                  right={0}
                />
                <Column
                  className="post3"
                  layoutGravity={11}
                  gravity={0}
                  mainAxisAlignment={"start"}
                  crossAxisAlignment={"start"}
                  width={301}
                  isExpanded={true}
                  left={16}
                  right={0}
                >
                  <Text
                    className="figmadesign3"
                    layoutGravity={33}
                    gravity={1}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={301}
                    isExpanded={0}
                    left={0}
                    right={0}
                  >
                    {STRINGS["lbl_figmadesign"] || ""}
                  </Text>
                  <Text
                    className="adesignplatfo4"
                    layoutGravity={33}
                    gravity={1}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={301}
                    isExpanded={0}
                    left={0}
                    right={0}
                  >
                    {STRINGS["msg_a_design_platfo"] || ""}
                  </Text>
                  <Row
                    className="icons3"
                    layoutGravity={33}
                    gravity={0}
                    mainAxisAlignment={"start"}
                    crossAxisAlignment={"start"}
                    width={301}
                    isExpanded={0}
                    left={0}
                    right={0}
                  >
                    <Row
                      className="icon7"
                      layoutGravity={11}
                      gravity={0}
                      mainAxisAlignment={"start"}
                      crossAxisAlignment={"center"}
                      width={68}
                      isExpanded={0}
                      left={0}
                      right={0}
                    >
                      <Image
                        src="img_iconcomment.svg"
                        alt="IconComment"
                        className="iconcomment5"
                        layoutGravity={11}
                        gravity={0}
                        mainAxisAlignment={""}
                        crossAxisAlignment={""}
                        width={48}
                        left={0}
                        right={0}
                      />
                      <Text
                        className="b17"
                        layoutGravity={10}
                        gravity={1}
                        mainAxisAlignment={""}
                        crossAxisAlignment={""}
                        width={12}
                        isExpanded={true}
                        left={8}
                        right={0}
                      >
                        {STRINGS["lbl_1"] || ""}
                      </Text>
                    </Row>
                    <Row
                      className="icon8"
                      layoutGravity={11}
                      gravity={0}
                      mainAxisAlignment={"start"}
                      crossAxisAlignment={"center"}
                      width={79}
                      isExpanded={0}
                      left={34}
                      right={0}
                    >
                      <Image
                        src="img_iconrepost.svg"
                        alt="IconRepost"
                        className="iconrepost4"
                        layoutGravity={11}
                        gravity={0}
                        mainAxisAlignment={""}
                        crossAxisAlignment={""}
                        width={48}
                        left={0}
                        right={0}
                      />
                      <Text
                        className="c114"
                        layoutGravity={10}
                        gravity={1}
                        mainAxisAlignment={""}
                        crossAxisAlignment={""}
                        width={23}
                        isExpanded={true}
                        left={8}
                        right={0}
                      >
                        {STRINGS["lbl_11"] || ""}
                      </Text>
                    </Row>
                    <Row
                      className="icon9"
                      layoutGravity={11}
                      gravity={0}
                      mainAxisAlignment={"start"}
                      crossAxisAlignment={"center"}
                      width={86}
                      isExpanded={true}
                      left={34}
                      right={0}
                    >
                      <Image
                        src="img_iconlike.svg"
                        alt="IconLike"
                        className="iconlike5"
                        layoutGravity={11}
                        gravity={0}
                        mainAxisAlignment={""}
                        crossAxisAlignment={""}
                        width={48}
                        left={0}
                        right={0}
                      />
                      <Text
                        className="c674"
                        layoutGravity={10}
                        gravity={1}
                        mainAxisAlignment={""}
                        crossAxisAlignment={""}
                        width={30}
                        isExpanded={true}
                        left={8}
                        right={0}
                      >
                        {STRINGS["lbl_67"] || ""}
                      </Text>
                    </Row>
                  </Row>
                </Column>
              </Row>
            </Column>
            <Column
              className="postcontainer4"
              layoutGravity={5}
              gravity={0}
              mainAxisAlignment={"start"}
              crossAxisAlignment={"start"}
              width={461}
              isExpanded={0}
              left={593}
              right={100}
            >
              <Row
                className="innercontainer5"
                layoutGravity={33}
                gravity={0}
                mainAxisAlignment={"center"}
                crossAxisAlignment={"start"}
                width={461}
                isExpanded={0}
                left={0}
                right={0}
              >
                <Image
                  src="img_avatar_2.svg"
                  alt="Avatar"
                  className="avatar4"
                  layoutGravity={11}
                  gravity={0}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={80}
                  left={0}
                  right={0}
                />
                <Column
                  className="post4"
                  layoutGravity={11}
                  gravity={0}
                  mainAxisAlignment={"start"}
                  crossAxisAlignment={"start"}
                  width={301}
                  isExpanded={true}
                  left={16}
                  right={0}
                >
                  <Text
                    className="figmadesign4"
                    layoutGravity={33}
                    gravity={1}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={301}
                    isExpanded={0}
                    left={0}
                    right={0}
                  >
                    {STRINGS["lbl_figmadesign"] || ""}
                  </Text>
                  <Text
                    className="adesignplatfo5"
                    layoutGravity={33}
                    gravity={1}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={301}
                    isExpanded={0}
                    left={0}
                    right={0}
                  >
                    {STRINGS["msg_a_design_platfo"] || ""}
                  </Text>
                  <Row
                    className="icons4"
                    layoutGravity={33}
                    gravity={0}
                    mainAxisAlignment={"start"}
                    crossAxisAlignment={"start"}
                    width={301}
                    isExpanded={0}
                    left={0}
                    right={0}
                  >
                    <Row
                      className="icon10"
                      layoutGravity={11}
                      gravity={0}
                      mainAxisAlignment={"start"}
                      crossAxisAlignment={"center"}
                      width={68}
                      isExpanded={0}
                      left={0}
                      right={0}
                    >
                      <Image
                        src="img_iconcomment.svg"
                        alt="IconComment"
                        className="iconcomment6"
                        layoutGravity={11}
                        gravity={0}
                        mainAxisAlignment={""}
                        crossAxisAlignment={""}
                        width={48}
                        left={0}
                        right={0}
                      />
                      <Text
                        className="b18"
                        layoutGravity={10}
                        gravity={1}
                        mainAxisAlignment={""}
                        crossAxisAlignment={""}
                        width={12}
                        isExpanded={true}
                        left={8}
                        right={0}
                      >
                        {STRINGS["lbl_1"] || ""}
                      </Text>
                    </Row>
                    <Row
                      className="icon11"
                      layoutGravity={11}
                      gravity={0}
                      mainAxisAlignment={"start"}
                      crossAxisAlignment={"center"}
                      width={79}
                      isExpanded={0}
                      left={34}
                      right={0}
                    >
                      <Image
                        src="img_iconrepost.svg"
                        alt="IconRepost"
                        className="iconrepost5"
                        layoutGravity={11}
                        gravity={0}
                        mainAxisAlignment={""}
                        crossAxisAlignment={""}
                        width={48}
                        left={0}
                        right={0}
                      />
                      <Text
                        className="c115"
                        layoutGravity={10}
                        gravity={1}
                        mainAxisAlignment={""}
                        crossAxisAlignment={""}
                        width={23}
                        isExpanded={true}
                        left={8}
                        right={0}
                      >
                        {STRINGS["lbl_11"] || ""}
                      </Text>
                    </Row>
                    <Row
                      className="icon12"
                      layoutGravity={11}
                      gravity={0}
                      mainAxisAlignment={"start"}
                      crossAxisAlignment={"center"}
                      width={86}
                      isExpanded={true}
                      left={34}
                      right={0}
                    >
                      <Image
                        src="img_iconlike.svg"
                        alt="IconLike"
                        className="iconlike6"
                        layoutGravity={11}
                        gravity={0}
                        mainAxisAlignment={""}
                        crossAxisAlignment={""}
                        width={48}
                        left={0}
                        right={0}
                      />
                      <Text
                        className="c675"
                        layoutGravity={10}
                        gravity={1}
                        mainAxisAlignment={""}
                        crossAxisAlignment={""}
                        width={30}
                        isExpanded={true}
                        left={8}
                        right={0}
                      >
                        {STRINGS["lbl_67"] || ""}
                      </Text>
                    </Row>
                  </Row>
                </Column>
              </Row>
            </Column>
          </List>
          <Row
            className="group1908"
            layoutGravity={33}
            gravity={0}
            mainAxisAlignment={"center"}
            crossAxisAlignment={"start"}
            width={1154}
            isExpanded={0}
            left={0}
            right={0}
          >
            <Image
              src="img_arrow_8.svg"
              alt="Arrow"
              className="arrow10"
              layoutGravity={11}
              gravity={0}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={39.62}
              left={0}
              right={0}
            />
            <Text
              className="trysettingeac"
              layoutGravity={11}
              gravity={3}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={437}
              isExpanded={true}
              left={35}
              right={0}
            >
              {STRINGS["msg_try_setting_eac"] || ""}
            </Text>
            <Image
              src="img_arrow_7.svg"
              alt="Arrow"
              className="arrow11"
              layoutGravity={11}
              gravity={0}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={39.62}
              left={34}
              right={0}
            />
          </Row>
        </Column>
      </Row>
    </Column>
  );
};

export default Resizing2Page;
