import React from "react";
import { STRINGS } from "../../constants/string";
import { Row } from "../../components/Row";
import { Column } from "../../components/Column";
import { Text } from "../../components/Text";
import { TablesStep3 } from "../../components/TablesStep3";
import { Image } from "../../components/Image";
import { List } from "../../components/List";
import { Input } from "../../components/Input";
import { Line } from "../../components/Line";

const IndividualPaddingPage = () => {
  return (
    <Row
      className="individualpadd3"
      layoutGravity={0}
      gravity={0}
      mainAxisAlignment={"start"}
      crossAxisAlignment={"center"}
      width={1920}
      isExpanded={0}
      left={0}
      right={0}
    >
      <Column
        className="copy25"
        layoutGravity={11}
        gravity={0}
        mainAxisAlignment={"center"}
        crossAxisAlignment={"center"}
        width={484}
        isExpanded={0}
        left={0}
        right={0}
      >
        <Text
          className="individualpadd4"
          layoutGravity={12}
          gravity={1}
          mainAxisAlignment={""}
          crossAxisAlignment={""}
          width={340}
          isExpanded={0}
          left={0}
          right={0}
        >
          {STRINGS["msg_individual_padd"] || ""}
        </Text>
        <Text
          className="toprightbot"
          layoutGravity={12}
          gravity={1}
          mainAxisAlignment={""}
          crossAxisAlignment={""}
          width={340}
          isExpanded={0}
          left={0}
          right={0}
        >
          {STRINGS["msg_top_right_bot"] || ""}
        </Text>
        <Column
          className="steps5"
          layoutGravity={12}
          gravity={0}
          mainAxisAlignment={"start"}
          crossAxisAlignment={"start"}
          width={340}
          isExpanded={0}
          left={0}
          right={0}
        >
          <TablesStep3
            children={STRINGS["lbl_1"] || ""}
            children1={STRINGS["msg_select_the_adj"] || ""}
          />
          <Row
            className="step26"
            layoutGravity={33}
            gravity={0}
            mainAxisAlignment={"start"}
            crossAxisAlignment={"start"}
            width={340}
            isExpanded={0}
            left={0}
            right={0}
          >
            <Column
              className="bullet18"
              layoutGravity={11}
              gravity={0}
              mainAxisAlignment={"start"}
              crossAxisAlignment={"start"}
              width={42.67}
              isExpanded={0}
              left={0}
              right={0}
            >
              <Text
                className="b27"
                layoutGravity={33}
                gravity={9}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={42.67}
                isExpanded={0}
                left={0}
                right={0}
              >
                {STRINGS["lbl_2"] || ""}
              </Text>
            </Column>
            <div
              className="group144"
              layoutGravity={11}
              gravity={0}
              width={276}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              isExpanded={true}
              type="HorizontalScroll"
            >
              <Column
                className="listitem5"
                layoutGravity={1}
                gravity={0}
                mainAxisAlignment={"end"}
                crossAxisAlignment={"start"}
                width={276}
                isExpanded={0}
                left={0}
                right={0}
              >
                <Text
                  className="clickonthene"
                  layoutGravity={12}
                  gravity={1}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={286.67}
                  isExpanded={0}
                  left={0}
                  right={0}
                >
                  {STRINGS["msg_click_on_the_ne"] || ""}
                </Text>
                <Image
                  src="img_image23.png"
                  alt="image23"
                  className="image23"
                  layoutGravity={33}
                  gravity={0}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={240}
                  left={0}
                  right={36}
                />
              </Column>
            </div>
          </Row>
        </Column>
      </Column>
      <Row
        className="group139"
        layoutGravity={10}
        gravity={0}
        mainAxisAlignment={"start"}
        crossAxisAlignment={"center"}
        width={485.5}
        isExpanded={true}
        left={106}
        right={0}
      >
        <Text
          className="tryindentingt"
          layoutGravity={22}
          gravity={1}
          mainAxisAlignment={""}
          crossAxisAlignment={""}
          width={302}
          isExpanded={true}
          left={0}
          right={0}
        >
          {STRINGS["msg_try_indenting_t"] || ""}
        </Text>
        <Image
          src="img_vector86.svg"
          alt="Vector86"
          className="vector86"
          layoutGravity={10}
          gravity={0}
          mainAxisAlignment={""}
          crossAxisAlignment={""}
          width={141.5}
          left={10}
          right={0}
        />
      </Row>
      <Column
        className="sidebarnav"
        layoutGravity={10}
        gravity={0}
        mainAxisAlignment={"center"}
        crossAxisAlignment={"center"}
        width={372}
        isExpanded={0}
        left={36.5}
        right={0}
      >
        <Row
          className="logolockup"
          layoutGravity={33}
          gravity={0}
          mainAxisAlignment={"center"}
          crossAxisAlignment={"start"}
          width={372}
          isExpanded={0}
          left={0}
          right={0}
        >
          <Image
            src="img_widgco.svg"
            alt="Widgco"
            className="widgco"
            layoutGravity={10}
            gravity={0}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={48}
            left={0}
            right={0}
          />
          <Text
            className="widgco2"
            layoutGravity={11}
            gravity={4}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={234}
            isExpanded={true}
            left={18}
            right={0}
          >
            {STRINGS["lbl_widgco"] || ""}
          </Text>
        </Row>
        <Column
          className="menuitems"
          layoutGravity={12}
          gravity={0}
          mainAxisAlignment={"center"}
          crossAxisAlignment={"start"}
          width={300}
          isExpanded={0}
          left={36}
          right={36}
        >
          <Row
            className="home2"
            layoutGravity={33}
            gravity={0}
            mainAxisAlignment={"start"}
            crossAxisAlignment={"center"}
            width={300}
            isExpanded={0}
            left={0}
            right={0}
          >
            <Image
              src="img_iconhome_3.svg"
              alt="iconhome"
              className="iconhome4"
              layoutGravity={10}
              gravity={0}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={48}
              left={0}
              right={0}
            />
            <Text
              className="home3"
              layoutGravity={10}
              gravity={4}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={224}
              isExpanded={true}
              left={16}
              right={0}
            >
              {STRINGS["lbl_home"] || ""}
            </Text>
          </Row>
          <List
            className="group143"
            orientation="vertical"
            layoutGravity={33}
            gravity={0}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={300}
          >
            <Row
              className="recents"
              layoutGravity={1}
              gravity={0}
              mainAxisAlignment={"start"}
              crossAxisAlignment={"center"}
              width={300}
              isExpanded={0}
              left={0}
              right={0}
            >
              <Image
                src="img_iconclock.svg"
                alt="iconclock"
                className="iconclock"
                layoutGravity={10}
                gravity={0}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={48}
                left={0}
                right={0}
              />
              <Text
                className="recents2"
                layoutGravity={10}
                gravity={4}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={190}
                isExpanded={true}
                left={16}
                right={0}
              >
                {STRINGS["lbl_recents"] || ""}
              </Text>
              <Image
                src="img_vector85.svg"
                alt="Vector85"
                className="vector85"
                layoutGravity={10}
                gravity={0}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={18}
                left={16}
                right={0}
              />
            </Row>
            <Row
              className="security"
              layoutGravity={6}
              gravity={0}
              mainAxisAlignment={"start"}
              crossAxisAlignment={"center"}
              width={300}
              isExpanded={0}
              left={0}
              right={0}
            >
              <Image
                src="img_iconsettings.svg"
                alt="iconsettings"
                className="iconsettings"
                layoutGravity={10}
                gravity={0}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={48}
                left={0}
                right={0}
              />
              <Text
                className="settings"
                layoutGravity={10}
                gravity={4}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={190}
                isExpanded={true}
                left={16}
                right={0}
              >
                {STRINGS["lbl_settings"] || ""}
              </Text>
              <Image
                src="img_vector85_1.svg"
                alt="Vector85"
                className="vector852"
                layoutGravity={10}
                gravity={0}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={18}
                left={16}
                right={0}
              />
            </Row>
          </List>
          <Row
            className="adjustments"
            layoutGravity={33}
            gravity={0}
            mainAxisAlignment={"start"}
            crossAxisAlignment={"center"}
            width={300}
            isExpanded={0}
            left={0}
            right={0}
          >
            <Image
              src="img_iconconfigure.svg"
              alt="iconconfigure"
              className="iconconfigure"
              layoutGravity={10}
              gravity={0}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={48}
              left={0}
              right={0}
            />
            <Text
              className="adjustments2"
              layoutGravity={10}
              gravity={4}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={224}
              isExpanded={true}
              left={16}
              right={0}
            >
              {STRINGS["lbl_adjustments"] || ""}
            </Text>
          </Row>
          <Input
            className="group31"
            name="Group31"
            placeholder={STRINGS["lbl_security"] || ""}
            layoutGravity={33}
            gravity={4}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={300}
          ></Input>
          <Row
            className="volume"
            layoutGravity={33}
            gravity={0}
            mainAxisAlignment={"start"}
            crossAxisAlignment={"center"}
            width={300}
            isExpanded={0}
            left={0}
            right={0}
          >
            <Image
              src="img_iconvolume.svg"
              alt="iconvolume"
              className="iconvolume"
              layoutGravity={10}
              gravity={0}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={48}
              left={0}
              right={0}
            />
            <Text
              className="volume2"
              layoutGravity={10}
              gravity={4}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={224}
              isExpanded={true}
              left={16}
              right={0}
            >
              {STRINGS["lbl_volume"] || ""}
            </Text>
          </Row>
          <Row
            className="messages"
            layoutGravity={33}
            gravity={0}
            mainAxisAlignment={"start"}
            crossAxisAlignment={"center"}
            width={300}
            isExpanded={0}
            left={0}
            right={0}
          >
            <Image
              src="img_iconemail.svg"
              alt="iconemail"
              className="iconemail"
              layoutGravity={10}
              gravity={0}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={48}
              left={0}
              right={0}
            />
            <Text
              className="messages2"
              layoutGravity={10}
              gravity={4}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={190}
              isExpanded={true}
              left={16}
              right={0}
            >
              {STRINGS["lbl_messages"] || ""}
            </Text>
            <Image
              src="img_vector85.svg"
              alt="Vector85"
              className="vector853"
              layoutGravity={10}
              gravity={0}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={18}
              left={16}
              right={0}
            />
          </Row>
          <Row
            className="documents"
            layoutGravity={33}
            gravity={0}
            mainAxisAlignment={"start"}
            crossAxisAlignment={"center"}
            width={300}
            isExpanded={0}
            left={0}
            right={0}
          >
            <Image
              src="img_iconedit.svg"
              alt="iconedit"
              className="iconedit"
              layoutGravity={10}
              gravity={0}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={48}
              left={0}
              right={0}
            />
            <Text
              className="documents2"
              layoutGravity={10}
              gravity={4}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={224}
              isExpanded={true}
              left={16}
              right={0}
            >
              {STRINGS["lbl_documents"] || ""}
            </Text>
          </Row>
          <Row
            className="deleted"
            layoutGravity={33}
            gravity={0}
            mainAxisAlignment={"end"}
            crossAxisAlignment={"center"}
            width={300}
            isExpanded={0}
            left={0}
            right={0}
          >
            <Column
              className="group141"
              layoutGravity={10}
              gravity={0}
              mainAxisAlignment={"start"}
              crossAxisAlignment={"center"}
              width={21}
              isExpanded={0}
              left={0}
              right={0}
            >
              <Line
                className="ellipse4"
                layoutGravity={12}
                gravity={0}
                isExpanded={0}
                left={7.5}
                right={7.5}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={6}
              />
              <Column
                className="group142"
                layoutGravity={33}
                gravity={0}
                mainAxisAlignment={"start"}
                crossAxisAlignment={"start"}
                width={21}
                isExpanded={0}
                left={0}
                right={0}
              >
                <Line
                  className="line3"
                  layoutGravity={33}
                  gravity={0}
                  isExpanded={0}
                  left={0}
                  right={0}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={21}
                />
                <Row
                  className="group140"
                  layoutGravity={33}
                  gravity={0}
                  mainAxisAlignment={"spaceEvenly"}
                  crossAxisAlignment={"start"}
                  width={21}
                  isExpanded={0}
                  left={0}
                  right={0}
                >
                  <Line
                    className="line"
                    layoutGravity={11}
                    gravity={0}
                    isExpanded={0}
                    left={0}
                    right={0}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={1.5}
                  />
                  <Line
                    className="line2"
                    layoutGravity={11}
                    gravity={0}
                    isExpanded={0}
                    left={2.25}
                    right={0}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={1.5}
                  />
                  <Line
                    className="line32"
                    layoutGravity={11}
                    gravity={0}
                    isExpanded={0}
                    left={2.25}
                    right={0}
                    mainAxisAlignment={""}
                    crossAxisAlignment={""}
                    width={1.5}
                  />
                </Row>
              </Column>
            </Column>
            <Text
              className="deleted2"
              layoutGravity={10}
              gravity={4}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={224}
              isExpanded={true}
              left={29.5}
              right={0}
            >
              {STRINGS["lbl_deleted"] || ""}
            </Text>
          </Row>
        </Column>
      </Column>
    </Row>
  );
};

export default IndividualPaddingPage;
