import React from "react";
import { STRINGS } from "../../constants/string";
import { Column } from "../../components/Column";
import { Row } from "../../components/Row";
import { Text } from "../../components/Text";
import { Image } from "../../components/Image";
import { Line } from "../../components/Line";
import { Stack } from "../../components/Stack";
import { CheckBox } from "../../components/CheckBox";

const IndividualpaddingPage = () => {
  return (
    <Column
      className="individualpadd"
      layoutGravity={0}
      gravity={0}
      mainAxisAlignment={"start"}
      crossAxisAlignment={"start"}
      width={1920}
      isExpanded={0}
      left={0}
      right={0}
    >
      <Row
        className="group89"
        layoutGravity={33}
        gravity={0}
        mainAxisAlignment={"start"}
        crossAxisAlignment={"center"}
        width={1920}
        isExpanded={0}
        left={0}
        right={0}
      >
        <Column
          className="copy9"
          layoutGravity={11}
          gravity={0}
          mainAxisAlignment={"center"}
          crossAxisAlignment={"center"}
          width={484}
          isExpanded={0}
          left={0}
          right={0}
        >
          <Text
            className="individualpadd2"
            layoutGravity={12}
            gravity={1}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={340}
            isExpanded={0}
            left={72}
            right={72}
          >
            {STRINGS["msg_individual_padd"] || ""}
          </Text>
          <Text
            className="youcanadjust"
            layoutGravity={12}
            gravity={1}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={340}
            isExpanded={0}
            left={72}
            right={72}
          >
            {STRINGS["msg_you_can_adjust"] || ""}
          </Text>
          <Row
            className="step13"
            layoutGravity={33}
            gravity={0}
            mainAxisAlignment={"center"}
            crossAxisAlignment={"start"}
            width={484}
            isExpanded={0}
            left={0}
            right={0}
          >
            <Column
              className="bullet8"
              layoutGravity={11}
              gravity={0}
              mainAxisAlignment={"start"}
              crossAxisAlignment={"start"}
              width={42.67}
              isExpanded={0}
              left={0}
              right={0}
            >
              <Text
                className="b14"
                layoutGravity={33}
                gravity={9}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={42.67}
                isExpanded={0}
                left={0}
                right={0}
              >
                {STRINGS["lbl_1"] || ""}
              </Text>
            </Column>
            <div
              className="group93"
              layoutGravity={10}
              gravity={0}
              width={276}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              isExpanded={true}
              type="HorizontalScroll"
            >
              <Column
                className="listitem3"
                layoutGravity={4}
                gravity={0}
                mainAxisAlignment={"end"}
                crossAxisAlignment={"start"}
                width={276}
                isExpanded={0}
                left={0}
                right={0}
              >
                <Text
                  className="openthealignm"
                  layoutGravity={12}
                  gravity={1}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={286.67}
                  isExpanded={0}
                  left={0}
                  right={0}
                >
                  {STRINGS["msg_open_the_alignm"] || ""}
                </Text>
                <Image
                  src="img_ui.png"
                  alt="UI"
                  className="ui"
                  layoutGravity={33}
                  gravity={0}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={240}
                  left={0}
                  right={36}
                />
              </Column>
            </div>
          </Row>
          <Column
            className="tip"
            layoutGravity={12}
            gravity={0}
            mainAxisAlignment={"start"}
            crossAxisAlignment={"start"}
            width={340}
            isExpanded={0}
            left={72}
            right={72}
          >
            <Line
              className="frame1902"
              layoutGravity={33}
              gravity={0}
              isExpanded={0}
              left={0}
              right={0}
              mainAxisAlignment={""}
              crossAxisAlignment={""}
              width={340}
            />
            <Column
              className="group87"
              layoutGravity={33}
              gravity={0}
              mainAxisAlignment={"end"}
              crossAxisAlignment={"center"}
              width={340}
              isExpanded={0}
              left={0}
              right={0}
            >
              <Stack
                className="group91"
                layoutGravity={12}
                gravity={0}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={292}
                isExpanded={0}
                left={24}
                right={24}
              >
                <Text
                  className="tipyoucan"
                  layoutGravity={4}
                  gravity={1}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={292}
                  isExpanded={0}
                  left={0}
                  right={0}
                >
                  {STRINGS["msg_tip_you_can_ty"] || ""}
                </Text>
                <Image
                  src="img_image14.png"
                  alt="image14"
                  className="image14"
                  layoutGravity={3}
                  gravity={0}
                  mainAxisAlignment={""}
                  crossAxisAlignment={""}
                  width={241}
                  left={25}
                  right={26}
                />
              </Stack>
              <Line
                className="frame1903"
                layoutGravity={33}
                gravity={0}
                isExpanded={0}
                left={0}
                right={0}
                mainAxisAlignment={""}
                crossAxisAlignment={""}
                width={340}
              />
            </Column>
          </Column>
        </Column>
        <Stack
          className="group92"
          layoutGravity={10}
          gravity={0}
          mainAxisAlignment={""}
          crossAxisAlignment={""}
          width={197.5}
          isExpanded={0}
          left={282}
          right={0}
        >
          <Image
            src="img_arrow_4.svg"
            alt="Arrow"
            className="arrow6"
            layoutGravity={5}
            gravity={0}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={114.58}
            left={82.91998}
            right={0}
          />
          <Text
            className="tryithere"
            layoutGravity={1}
            gravity={3}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={122}
            isExpanded={0}
            left={0}
            right={75.5}
          >
            {STRINGS["lbl_try_it_here"] || ""}
          </Text>
        </Stack>
        <Column
          className="group90"
          layoutGravity={10}
          gravity={0}
          mainAxisAlignment={"start"}
          crossAxisAlignment={"end"}
          width={501}
          isExpanded={true}
          left={7.5}
          right={0}
        >
          <Text
            className="thingstodo"
            layoutGravity={33}
            gravity={1}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={501}
            isExpanded={0}
            left={0}
            right={0}
          >
            {STRINGS["lbl_things_to_do"] || ""}
          </Text>
          <CheckBox
            className="group13"
            label={STRINGS["lbl_buy_groceries"] || ""}
            name="Group13"
            layoutGravity={12}
            gravity={1}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={493}
          ></CheckBox>
          <CheckBox
            className="group14"
            label={STRINGS["lbl_popcorn"] || ""}
            name="Group14"
            layoutGravity={44}
            gravity={1}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={439}
          ></CheckBox>
          <CheckBox
            className="group15"
            label={STRINGS["lbl_chocolate"] || ""}
            name="Group15"
            layoutGravity={44}
            gravity={1}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={439}
          ></CheckBox>
          <CheckBox
            className="group16"
            label={STRINGS["lbl_kale"] || ""}
            name="Group16"
            layoutGravity={44}
            gravity={1}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={439}
          ></CheckBox>
          <CheckBox
            className="group17"
            label={STRINGS["msg_take_pua_out_on"] || ""}
            name="Group17"
            layoutGravity={12}
            gravity={1}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={493}
          ></CheckBox>
          <Text
            className="thingstodo2"
            layoutGravity={33}
            gravity={1}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={501}
            isExpanded={0}
            left={0}
            right={0}
          >
            {STRINGS["lbl_things_to_do"] || ""}
          </Text>
          <CheckBox
            className="group18"
            label={STRINGS["lbl_buy_groceries"] || ""}
            name="Group18"
            layoutGravity={12}
            gravity={1}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={493}
          ></CheckBox>
          <CheckBox
            className="group19"
            label={STRINGS["lbl_popcorn"] || ""}
            name="Group19"
            layoutGravity={12}
            gravity={1}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={493}
          ></CheckBox>
          <CheckBox
            className="group20"
            label={STRINGS["lbl_chocolate"] || ""}
            name="Group20"
            layoutGravity={12}
            gravity={1}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={493}
          ></CheckBox>
          <CheckBox
            className="group21"
            label={STRINGS["lbl_kale"] || ""}
            name="Group21"
            layoutGravity={12}
            gravity={1}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={493}
          ></CheckBox>
          <CheckBox
            className="group22"
            label={STRINGS["msg_take_pua_out_on"] || ""}
            name="Group22"
            layoutGravity={12}
            gravity={1}
            mainAxisAlignment={""}
            crossAxisAlignment={""}
            width={493}
          ></CheckBox>
        </Column>
      </Row>
    </Column>
  );
};

export default IndividualpaddingPage;
